// Mi Amigo — 多言語データ（日本語 / English / Español）
// 写真は img フィールドに "img/<id>.jpg" or 画像URL。未指定は emoji プレースホルダー。
// 価格(price)は USD のおおよその目安。
window.MI_AMIGO_DATA = {
  listings: [
    { id:"delagente-coffee", type:"exp", emoji:"☕", price:40, unit:"USD", maxSlots:8,
      area:"San Miguel Escobar（アンティグア近郊）", link:"https://www.delagente.org/", img:"",
      title:{ ja:"De La Gente コーヒー農園＆コミュニティ体験", en:"De La Gente Coffee Farm & Community Tour", es:"Finca de café y comunidad De La Gente" },
      desc:{ ja:"生産者協同組合と歩く社会的企業のツアー。摘み取り〜焙煎、コミュニティ支援の現場まで",
             en:"A social-enterprise tour with farmer cooperatives: from picking to roasting, and the community behind it.",
             es:"Un tour de empresa social con cooperativas: de la cosecha al tueste, y la comunidad detrás." } },
    { id:"chocomuseo-bar", type:"exp", emoji:"🍫", price:33, unit:"USD", maxSlots:12,
      area:"4a calle oriente", link:"https://www.chocomuseo.com/", img:"",
      title:{ ja:"ChocoMuseo Bean-to-Bar チョコ ワークショップ", en:"ChocoMuseo Bean-to-Bar Chocolate Workshop", es:"Taller de chocolate Bean-to-Bar ChocoMuseo" },
      desc:{ ja:"カカオ豆から板チョコまで（約2時間）。手作り120gをお持ち帰り",
             en:"From cacao bean to bar (about 2 hours). Take home 120g you made yourself.",
             es:"Del grano de cacao a la barra (unas 2 horas). Llévate 120g hechos por ti." } },
    { id:"kakaw-weaving", type:"exp", emoji:"🧵", price:45, unit:"USD", maxSlots:5,
      area:"アンティグア中心部 / Antigua centro", link:"https://kakawdesigns.com/", img:"",
      title:{ ja:"Kakaw Designs バックストラップ織り ワークショップ", en:"Kakaw Designs Backstrap Weaving Workshop", es:"Taller de telar de cintura Kakaw Designs" },
      desc:{ ja:"マヤの腰機織りを庭で学ぶ（英・西対応）。福祉×ウイピル アップサイクルと連動",
             en:"Learn Maya backstrap weaving in a garden (EN/ES). Linked to our huipil upcycling project.",
             es:"Aprende el telar de cintura maya en un jardín (EN/ES). Ligado a nuestro proyecto de huipil." } },
    { id:"food-tour", type:"exp", emoji:"🥘", price:55, unit:"USD", maxSlots:10,
      area:"アンティグア旧市街 / Antigua casco", link:"", img:"",
      title:{ ja:"アンティグア ストリートフード ツアー", en:"Antigua Street Food Tour", es:"Tour de comida callejera de Antigua" },
      desc:{ ja:"ガイドと市場〜名店を巡り約10品を試食。少人数制",
             en:"Taste about 10 dishes from market to favorite spots with a guide. Small groups.",
             es:"Prueba unos 10 platillos del mercado a los mejores lugares con un guía. Grupos pequeños." } },
    { id:"kombu-ramen", type:"food", emoji:"🍜", price:14, unit:"USD", maxSlots:16,
      area:"3a calle oriente #19D", link:"https://komburamenshop.com/", img:"",
      title:{ ja:"Kombu Ramen Shop 席予約", en:"Kombu Ramen Shop Reservation", es:"Reserva en Kombu Ramen Shop" },
      desc:{ ja:"グアテマラ初のラーメン店。地元産小麦の自家製麺と6種のラーメン",
             en:"Guatemala's first ramen shop. House-made noodles from local flour, 6 kinds of ramen.",
             es:"El primer ramen de Guatemala. Fideos caseros de harina local y 6 tipos de ramen." } },
    { id:"barbara-hostel", type:"stay", emoji:"🛏️", price:15, unit:"USD", maxSlots:10,
      area:"アンティグア中心部 / Antigua centro", link:"", img:"",
      title:{ ja:"Barbara's Boutique Hostel（1泊・ドミトリー）", en:"Barbara's Boutique Hostel (dorm, 1 night)", es:"Barbara's Boutique Hostel (dormitorio, 1 noche)" },
      desc:{ ja:"コロニアル様式の邸宅。屋上テラスからアグア・フエゴ・アカテナンゴの3火山",
             en:"A colonial house with a rooftop overlooking the Agua, Fuego and Acatenango volcanoes.",
             es:"Una casa colonial con azotea y vista a los volcanes Agua, Fuego y Acatenango." } },
  ],

  // 謎解きの全体情報（謎は下の guide.route.stops から生成）
  quest: {
    title:  { ja:"アンティグア 歴史ミステリー・ラリー", en:"Antigua History Mystery Rally", es:"Rally del misterio histórico de Antigua" },
    reward: { ja:"7/10クリアで次のダンジョン（次の世界遺産）が出現！", en:"Clear 7/10 to make the next dungeon (heritage site) appear!", es:"¡Completa 7/10 para que aparezca la próxima mazmorra (sitio del patrimonio)!" },
  },

  // 音声ウォーキングガイド ＝ 謎解きスポット（多言語）
  guide: {
    route: {
      title: { ja:"アンティグア 街歩き音声ガイド", en:"Antigua Walking Audio Guide", es:"Audioguía a pie de Antigua" },
      intro: {
        ja:"世界遺産の街アンティグアを約10スポット巡ります。再生すると物語が流れ、謎解きでは“その場所”の写真を撮って投稿します。",
        en:"Walk the UNESCO city of Antigua across ~10 stops. Play to hear each story; in the rally, photograph the place and post it.",
        es:"Recorre la ciudad Patrimonio de Antigua en ~10 paradas. Reproduce para oír la historia; en el rally, fotografía el lugar y publícalo.",
      },
      stops: [
        { id:"s1", emoji:"🌉", lat:14.5586, lng:-90.7339,
          title:{ ja:"サンタ・カタリナのアーチ", en:"Santa Catalina Arch", es:"Arco de Santa Catalina" },
          text:{ ja:"アンティグアの象徴、黄色いアーチ。17世紀、修道女たちが通りに姿を見せず行き来できるよう、修道院と学校をつなぐ橋として造られました。背後にはアグア火山がそびえます。",
                 en:"Antigua's icon, the yellow arch. Built in the 17th century so cloistered nuns could cross the street unseen, linking the convent and school. Volcán de Agua rises behind it.",
                 es:"El ícono de Antigua, el arco amarillo. Construido en el siglo XVII para que las monjas de clausura cruzaran la calle sin ser vistas. Detrás se alza el Volcán de Agua." },
          riddle:{ ja:"修道女たちが人目を避けて通りを渡れるよう造られた『黄色いアーチ』。その姿を写真に撮ろう。",
                   en:"Find the yellow arch built so cloistered nuns could cross the street unseen. Photograph it.",
                   es:"Encuentra el arco amarillo hecho para que las monjas cruzaran sin ser vistas. Fotografíalo." } },
        { id:"s2", emoji:"⛲", lat:14.5564, lng:-90.7339,
          title:{ ja:"中央公園（プラサ・マヨール）", en:"Central Park (Plaza Mayor)", es:"Parque Central (Plaza Mayor)" },
          text:{ ja:"街の心臓部。中央には「人魚の噴水」が立ち、大聖堂や旧総督府に囲まれています。人々が集い、休む、アンティグアの暮らしの中心です。",
                 en:"The heart of the city. At its center stands the Fountain of the Sirens, surrounded by the cathedral and old palaces.",
                 es:"El corazón de la ciudad. En su centro está la Fuente de las Sirenas, rodeada por la catedral y los palacios." },
          riddle:{ ja:"街の中心、『人魚の噴水』が立つ広場。噴水を写真に撮ろう。",
                   en:"The central plaza with the Fountain of the Sirens. Photograph the fountain.",
                   es:"La plaza central con la Fuente de las Sirenas. Fotografía la fuente." } },
        { id:"s3", emoji:"⛪", lat:14.5566, lng:-90.7327,
          title:{ ja:"サン・ホセ大聖堂（旧聖堂跡）", en:"Cathedral of San José (ruins)", es:"Catedral de San José (ruinas)" },
          text:{ ja:"かつて中米最大級を誇った聖堂。1773年の大地震で崩れ、今もその壮大な廃墟が残ります。",
                 en:"Once among the grandest cathedrals in Central America, toppled by the 1773 earthquake. Its majestic ruins still stand.",
                 es:"Una de las catedrales más grandiosas de Centroamérica, derribada por el terremoto de 1773. Sus ruinas aún se alzan." },
          riddle:{ ja:"1773年の地震で崩れた、かつて中米最大級の聖堂跡。その廃墟を写真に撮ろう。",
                   en:"The ruins of what was one of Central America's grandest cathedrals, felled in 1773. Photograph them.",
                   es:"Las ruinas de una de las mayores catedrales, caída en 1773. Fotografíalas." } },
        { id:"s4", emoji:"🏛️", lat:14.5560, lng:-90.7335,
          title:{ ja:"総督府（カピタネス・ヘネラレス宮殿）", en:"Palace of the Captains General", es:"Palacio de los Capitanes Generales" },
          text:{ ja:"スペイン植民地時代、グアテマラ総督領を治めた政庁。長く連なるアーチの回廊が当時の権力を物語ります。",
                 en:"The seat of Spanish colonial government. Its long arcade of arches speaks to the reach of that power.",
                 es:"La sede del gobierno colonial español. Su larga arcada habla del alcance de aquel poder." },
          riddle:{ ja:"長いアーチの回廊が続く、植民地時代の総督府。その回廊を写真に撮ろう。",
                   en:"The colonial palace with a long arcade of arches. Photograph the arcade.",
                   es:"El palacio colonial con una larga arcada. Fotografía la arcada." } },
        { id:"s5", emoji:"💛", lat:14.5601, lng:-90.7344,
          title:{ ja:"ラ・メルセー教会", en:"La Merced Church", es:"Iglesia de La Merced" },
          text:{ ja:"鮮やかな黄色と白の漆喰装飾が美しいバロック教会。地震に耐えるよう低く頑丈に設計されました。",
                 en:"A Baroque church famed for its vivid yellow facade and white stucco, built low and strong to resist earthquakes.",
                 es:"Una iglesia barroca célebre por su fachada amarilla y estuco blanco, baja y fuerte contra terremotos." },
          riddle:{ ja:"鮮やかな黄色のバロック教会。その正面（ファサード）を写真に撮ろう。",
                   en:"The vivid yellow Baroque church. Photograph its facade.",
                   es:"La iglesia barroca amarilla. Fotografía su fachada." } },
        { id:"s6", emoji:"🏚️", lat:14.5588, lng:-90.7316,
          title:{ ja:"カプチナス修道院", en:"Las Capuchinas Convent", es:"Convento de las Capuchinas" },
          text:{ ja:"保存状態の良い修道院。円形に並ぶ修道女の小部屋「塔」が珍しく、静寂と祈りの暮らしを今に伝えます。",
                 en:"A well-preserved convent. Its unusual circular 'tower' of nuns' cells conveys a life of silence and prayer.",
                 es:"Un convento bien conservado. Su singular 'torre' circular de celdas evoca el silencio y la oración." },
          riddle:{ ja:"円形に小部屋が並ぶ珍しい修道院。その中庭か塔を写真に撮ろう。",
                   en:"The convent with an unusual circular tower of cells. Photograph the courtyard or tower.",
                   es:"El convento con una torre circular de celdas. Fotografía el patio o la torre." } },
        { id:"s7", emoji:"✝️", lat:14.5650, lng:-90.7300,
          title:{ ja:"クルスの丘（展望台）", en:"Hill of the Cross (viewpoint)", es:"Cerro de la Cruz (mirador)" },
          text:{ ja:"街を見下ろす丘の上の十字架。アンティグアの碁盤の街並みと、その先のアグア火山が一直線に並ぶ絶景です。",
                 en:"A cross on the hill above the city, where Antigua's grid lines up with Volcán de Agua beyond.",
                 es:"Una cruz sobre la colina, donde la cuadrícula de Antigua se alinea con el Volcán de Agua." },
          riddle:{ ja:"丘の上の十字架から、街とアグア火山が一直線に見える展望。その景色を写真に撮ろう。",
                   en:"The hilltop cross where city and Volcán de Agua align. Photograph the view.",
                   es:"La cruz en la colina donde la ciudad y el volcán se alinean. Fotografía la vista." } },
        { id:"s8", emoji:"🙏", lat:14.5535, lng:-90.7313,
          title:{ ja:"サン・フランシスコ教会（エルマノ・ペドロ）", en:"San Francisco Church (Hermano Pedro)", es:"Iglesia de San Francisco (Hermano Pedro)" },
          text:{ ja:"中米初の聖人、エルマノ・ペドロが眠る巡礼地。今も多くの人が願いを胸に祈りを捧げます。",
                 en:"A pilgrimage site holding the tomb of Hermano Pedro, the first saint of Central America.",
                 es:"Un sitio de peregrinación con la tumba del Hermano Pedro, el primer santo de Centroamérica." },
          riddle:{ ja:"中米初の聖人エルマノ・ペドロが眠る教会。その外観を写真に撮ろう。",
                   en:"The church holding the tomb of Hermano Pedro, the first saint. Photograph its exterior.",
                   es:"La iglesia con la tumba del Hermano Pedro. Fotografía su exterior." } },
        { id:"s9", emoji:"💧", lat:14.5560, lng:-90.7300,
          title:{ ja:"タンケ・ラ・ウニオン（洗濯場）", en:"Tanque La Unión (wash basins)", es:"Tanque La Unión (lavaderos)" },
          text:{ ja:"石造りの公共洗濯場。植民地時代から人々が洗濯や語らいに集った場所で、今も地元の暮らしが息づいています。",
                 en:"Public stone wash basins where people have gathered to wash and talk since colonial times.",
                 es:"Lavaderos públicos de piedra donde la gente se reúne a lavar y conversar desde la colonia." },
          riddle:{ ja:"今も使われる石造りの公共洗濯場。その水場を写真に撮ろう。",
                   en:"The stone public wash basins still in use today. Photograph them.",
                   es:"Los lavaderos públicos de piedra aún en uso. Fotografíalos." } },
        { id:"s10", emoji:"🧶", lat:14.5558, lng:-90.7352,
          title:{ ja:"工芸市場（ウイピルの織物）", en:"Crafts Market (Huipil textiles)", es:"Mercado de Artesanías (huipiles)" },
          text:{ ja:"色鮮やかなマヤの織物「ウイピル」が並ぶ市場。一枚一枚が村ごとの模様を持ち、作り手の物語を宿しています。",
                 en:"A market bright with Maya 'huipil' textiles, each carrying the pattern of its village.",
                 es:"Un mercado lleno de textiles mayas 'huipiles', cada uno con el patrón de su pueblo." },
          riddle:{ ja:"色鮮やかなウイピルが並ぶ工芸市場。お気に入りの織物を写真に撮ろう。",
                   en:"The crafts market full of colorful huipiles. Photograph your favorite textile.",
                   es:"El mercado de artesanías lleno de huipiles. Fotografía tu textil favorito." } },
      ],
    },
    // 歴史を聴くシリーズ（場所に縛られない音声）
    history: [
      { id:"h1", emoji:"📜",
        title:{ ja:"グアテマラ小史", en:"A Short History of Guatemala", es:"Breve historia de Guatemala" },
        text:{ ja:"マヤ文明の地に、1524年スペインのアルバラードが征服者として現れ、植民地時代が始まりました。1821年に独立。先住民の文化と植民の歴史が、今のグアテマラに重なっています。",
               en:"On the land of the Maya, the Spaniard Alvarado arrived as conqueror in 1524, beginning the colonial era. Independence came in 1821.",
               es:"En tierra maya, el español Alvarado llegó como conquistador en 1524, iniciando la época colonial. La independencia llegó en 1821." } },
      { id:"h2", emoji:"🌋",
        title:{ ja:"アンティグア、遷都の物語", en:"Antigua: Why the Capital Moved", es:"Antigua: por qué se mudó la capital" },
        text:{ ja:"この街はかつて「サンティアゴ・デ・ロス・カバジェロス」という首都でした。1773年のサンタ・マルタ大地震で甚大な被害を受け、首都は現在のグアテマラシティへ移転。残されたこの街は「ラ・アンティグア（古い都）」と呼ばれるようになりました。",
               en:"This city was once the capital, 'Santiago de los Caballeros.' The 1773 earthquakes devastated it, the capital moved to today's Guatemala City, and what remained became 'La Antigua'.",
               es:"Esta ciudad fue la capital, 'Santiago de los Caballeros'. Los terremotos de 1773 la devastaron, la capital se trasladó y lo que quedó se llamó 'La Antigua'." } },
    ],
  },

  // なかま（コミュニティ）— デモのグループとメッセージ（ワールドホステル風）
  community: {
    groups: [
      { id:"g-tour", emoji:"🏛️", name:{ ja:"アンティグア世界遺産ツアー", en:"Antigua Heritage Tour", es:"Tour Patrimonio de Antigua" },
        seed:[
          { from:"Lucía", emoji:"🦜", text:"¡Hola amigos! ¿Alguien sube al Cerro de la Cruz al atardecer? 🌋" },
          { from:"Ken", emoji:"🎒", text:"行きたい！何時集合？" },
          { from:"Mia", emoji:"📷", text:"Just got the yellow arch shot, it's glowing today ✨" },
        ] },
      { id:"g-cafe", emoji:"☕", name:{ ja:"カフェ好き Amigos", en:"Café Amigos", es:"Amigos del café" },
        seed:[
          { from:"Sofía", emoji:"☕", text:"Fat Cat tiene el mejor cortado 👌" },
          { from:"Tomo", emoji:"🍰", text:"12 Onzas のケーキ最高だった！" },
        ] },
      { id:"g-lounge", emoji:"🌏", name:{ ja:"旅人ラウンジ", en:"Traveler Lounge", es:"Sala de viajeros" },
        seed:[
          { from:"Diego", emoji:"🎸", text:"Live music at the hostel tonight, todos invitados!" },
          { from:"Anna", emoji:"🌻", text:"Anyone heading to Lake Atitlán this weekend?" },
        ] },
    ],
  },

  // 世界遺産ステージ（地球儀ピン）。order順に解禁。questSource="antigua"はguide.route.stopsを謎解きに使う。
  // 第1ステージ=アンティグアのみコンテンツ実装済み。以降は near-future（コンテンツ近日）。
  stages: [
    { id:"antigua", order:1, questSource:"antigua", flag:"🇬🇹", lat:14.557, lng:-90.733,
      name:{ ja:"アンティグア・グアテマラ", en:"Antigua Guatemala", es:"Antigua Guatemala" },
      country:{ ja:"グアテマラ", en:"Guatemala", es:"Guatemala" } },
    { id:"tikal", order:2, flag:"🇬🇹", lat:17.222, lng:-89.623,
      name:{ ja:"ティカル遺跡", en:"Tikal", es:"Tikal" },
      country:{ ja:"グアテマラ", en:"Guatemala", es:"Guatemala" } },
    { id:"copan", order:3, flag:"🇭🇳", lat:14.838, lng:-89.142,
      name:{ ja:"コパンのマヤ遺跡", en:"Copán", es:"Copán" },
      country:{ ja:"ホンジュラス", en:"Honduras", es:"Honduras" } },
    { id:"chichen", order:4, flag:"🇲🇽", lat:20.683, lng:-88.568,
      name:{ ja:"チチェン・イッツァ", en:"Chichén Itzá", es:"Chichén Itzá" },
      country:{ ja:"メキシコ", en:"Mexico", es:"México" } },
    { id:"machupicchu", order:5, flag:"🇵🇪", lat:-13.163, lng:-72.545,
      name:{ ja:"マチュ・ピチュ", en:"Machu Picchu", es:"Machu Picchu" },
      country:{ ja:"ペルー", en:"Peru", es:"Perú" },
      content:{
        intro:{ ja:"標高2,430m、雲の上に築かれた15世紀インカ帝国の聖なる都市。段々畑と精巧な石組みが今も息づく『空中都市』。", en:"A sacred 15th-century Inca city built above the clouds at 2,430m — the 'city in the sky', with living terraces and masterful stonework.", es:"Ciudad sagrada inca del siglo XV sobre las nubes a 2.430 m — la 'ciudad en el cielo', con andenes y cantería magistral." },
        stops:[
          { id:"mp1", emoji:"🌅", lat:-13.1730, lng:-72.5409,
            title:{ ja:"太陽の門（インティ・プンク）", en:"Sun Gate (Inti Punku)", es:"Puerta del Sol (Inti Punku)" },
            narration:{ ja:"インカ道から遺跡へ入る石の門。夏至の朝、ここから昇る太陽が街を照らすように設計された。", en:"The stone gateway where the Inca Trail enters the site. At the solstice, the rising sun was designed to light the city from here.", es:"La puerta de piedra donde el Camino Inca entra al sitio. En el solsticio, el sol naciente iluminaba la ciudad desde aquí." },
            riddle:{ ja:"朝もやの中、遺跡全体が初めて見える石の門。そこからの絶景を撮ろう。", en:"The stone gate where you first see the whole site through morning mist. Capture the view.", es:"La puerta donde ves por primera vez todo el sitio entre la niebla. Captura la vista." } },
          { id:"mp2", emoji:"📷", lat:-13.1631, lng:-72.5460,
            title:{ ja:"見張り小屋（定番の展望）", en:"Guardhouse (classic view)", es:"Casa del Guardián (vista clásica)" },
            narration:{ ja:"ハガキでおなじみの全景はここから。茅葺きの小屋越しに、段々畑と街、背後のワイナピチュが一望できる。", en:"The postcard panorama is from here — terraces, the city and Huayna Picchu beyond the thatched hut.", es:"La panorámica de postal es desde aquí: andenes, la ciudad y el Huayna Picchu tras la choza." },
            riddle:{ ja:"段々畑越しに遺跡とワイナピチュを見下ろす定番ポイント。その全景を撮ろう。", en:"The classic spot overlooking the ruins and Huayna Picchu over the terraces. Shoot the panorama.", es:"El punto clásico sobre las ruinas y el Huayna Picchu. Toma la panorámica." } },
          { id:"mp3", emoji:"☀️", lat:-13.1636, lng:-72.5450,
            title:{ ja:"太陽の神殿（トレオン）", en:"Temple of the Sun (Torreón)", es:"Templo del Sol (Torreón)" },
            narration:{ ja:"曲線の石壁を持つ唯一の建物。窓は冬至・夏至の太陽が差し込む位置に正確に開けられている。", en:"The only building with curved walls. Its windows align precisely to the solstice sunrises.", es:"El único edificio de muros curvos. Sus ventanas se alinean con los amaneceres del solsticio." },
            riddle:{ ja:"丸みを帯びた曲線の石壁を持つ神殿。その美しい曲面を撮ろう。", en:"The temple with smooth curved stone walls. Capture that curve.", es:"El templo de muros curvos de piedra. Captura esa curva." } },
          { id:"mp4", emoji:"🪨", lat:-13.1631, lng:-72.5455,
            title:{ ja:"インティワタナ（日時計の石）", en:"Intihuatana (the sun stone)", es:"Intihuatana (la piedra solar)" },
            narration:{ ja:"『太陽をつなぐ石』。天文観測と儀式に使われたとされる聖なる切り出し石。", en:"The 'hitching post of the sun' — a carved sacred stone used for astronomy and ritual.", es:"El 'amarradero del sol': piedra sagrada tallada para astronomía y ritual." },
            riddle:{ ja:"一枚岩から削り出された『太陽をつなぐ石』。その角ばった姿を撮ろう。", en:"The 'sun stone' carved from a single rock. Capture its angular form.", es:"La 'piedra solar' tallada de una sola roca. Captura su forma angular." } },
          { id:"mp5", emoji:"🪟", lat:-13.1639, lng:-72.5448,
            title:{ ja:"三つの窓の神殿", en:"Temple of the Three Windows", es:"Templo de las Tres Ventanas" },
            narration:{ ja:"聖なる広場に面し、台形の三つの窓が東の谷へ開く。インカの世界観を表すといわれる。", en:"Facing the sacred plaza, three trapezoidal windows open to the eastern valley — said to express the Inca worldview.", es:"Frente a la plaza sagrada, tres ventanas trapezoidales abren al valle este; expresan la cosmovisión inca." },
            riddle:{ ja:"東の谷へ開く三つの台形の窓。その窓の並びを撮ろう。", en:"Three trapezoidal windows opening to the valley. Shoot the row of windows.", es:"Tres ventanas trapezoidales hacia el valle. Toma la hilera de ventanas." } },
          { id:"mp6", emoji:"⛰️", lat:-13.1610, lng:-72.5447,
            title:{ ja:"聖なる岩とワイナピチュ", en:"Sacred Rock & Huayna Picchu", es:"Roca Sagrada y Huayna Picchu" },
            narration:{ ja:"背後の山の稜線をかたどったと言われる大岩。ここからワイナピチュへの登山道が始まる。", en:"A great stone said to echo the mountain ridge behind it. The Huayna Picchu trail begins here.", es:"Una gran roca que evoca la cresta de la montaña. Aquí inicia el sendero al Huayna Picchu." },
            riddle:{ ja:"背後の山の形をなぞったような大きな聖なる岩。山と岩を一緒に撮ろう。", en:"The large sacred rock echoing the mountain behind. Shoot the rock with the peak.", es:"La gran roca sagrada que imita la montaña. Toma la roca con el pico." } },
        ],
        history:[
          { emoji:"📜", title:{ ja:"インカ帝国の聖地", en:"Sacred site of the Inca", es:"Sitio sagrado inca" },
            body:{ ja:"15世紀半ば、皇帝パチャクテクの時代に築かれた王の離宮とも聖域ともいわれる。スペイン人には知られず破壊を免れた。", en:"Built in the mid-1400s under emperor Pachacuti as a royal estate or sanctuary. Unknown to the Spanish, it escaped destruction.", es:"Construido a mediados del siglo XV bajo Pachacútec como hacienda real o santuario. Desconocido por los españoles, se salvó." } },
          { emoji:"🧭", title:{ ja:"1911年の『再発見』", en:"The 1911 'rediscovery'", es:"El 'redescubrimiento' de 1911" },
            body:{ ja:"1911年、米国人ハイラム・ビンガムが世界に紹介。実際には地元の人々は存在を知っていた。", en:"Brought to world attention in 1911 by Hiram Bingham — though local people already knew it was there.", es:"Dado a conocer al mundo en 1911 por Hiram Bingham, aunque los locales ya conocían su existencia." } },
          { emoji:"🏗️", title:{ ja:"地震に強い石組みと段々畑", en:"Quake-proof stonework & terraces", es:"Cantería antisísmica y andenes" },
            body:{ ja:"モルタルを使わず石を精密に積む『乾式石積み』。段々畑は水はけと土壌流出を防ぎ、急斜面での農業を可能にした。", en:"Mortar-free 'dry stone' fitting. Terraces drained water and stopped erosion, enabling farming on steep slopes.", es:"Ensamble en seco sin mortero. Los andenes drenaban el agua y evitaban la erosión, permitiendo cultivar en pendientes." } },
        ],
      } },
    { id:"cusco", order:6, flag:"🇵🇪", lat:-13.517, lng:-71.978,
      name:{ ja:"クスコ歴史地区", en:"Cusco", es:"Cusco" },
      country:{ ja:"ペルー", en:"Peru", es:"Perú" } },
    { id:"angkor", order:7, flag:"🇰🇭", lat:13.412, lng:103.866,
      name:{ ja:"アンコール・ワット", en:"Angkor Wat", es:"Angkor Wat" },
      country:{ ja:"カンボジア", en:"Cambodia", es:"Camboya" } },
    { id:"rome", order:8, flag:"🇮🇹", lat:41.890, lng:12.492,
      name:{ ja:"ローマ歴史地区", en:"Historic Rome", es:"Roma histórica" },
      country:{ ja:"イタリア", en:"Italy", es:"Italia" } },
    // 観光地（世界遺産ではない・グアテマラの人気スポット）
    { id:"atitlan", order:9, type:"sight", flag:"🇬🇹", lat:14.69, lng:-91.20,
      name:{ ja:"アティトラン湖", en:"Lake Atitlán", es:"Lago de Atitlán", zh:"阿蒂特兰湖" },
      country:{ ja:"グアテマラ", en:"Guatemala", es:"Guatemala", zh:"危地马拉" },
      blurb:{ ja:"3つの火山に囲まれた世界屈指の美しい湖。湖畔の村めぐりが楽しい。", en:"A stunning crater lake ringed by three volcanoes, with lakeside villages to hop between.", es:"Un bello lago de cráter rodeado por tres volcanes, con pueblos a la orilla para recorrer.", zh:"被三座火山环抱、世界屈指的美丽湖泊。环游湖畔的村庄十分惬意。" },
      content:{
        intro:{ ja:"標高1,500m、3つの火山に抱かれたアティトラン湖。湖畔には、それぞれ表情の違うマヤの村が点在する。織物の村、瞑想の村、信仰の村——ボートで渡り歩けば、ひとつの湖にいくつもの世界がある。数日かけてのんびり巡りたい。", en:"At 1,500 m, cradled by three volcanoes, Lake Atitlán is ringed by Maya villages, each with its own character. A village of weaving, a village of meditation, a village of devotion — hop by boat and you'll find many worlds on one lake. Take a few unhurried days.", es:"A 1.500 m y abrazado por tres volcanes, el lago de Atitlán está rodeado de pueblos mayas, cada uno con su carácter. Un pueblo del tejido, uno de la meditación, uno de la devoción: salta en lancha y hallarás muchos mundos en un solo lago. Recórrelo con calma, varios días.", zh:"海拔1,500米、被三座火山环抱的阿蒂特兰湖，湖畔散布着各具风情的玛雅村庄。织布之村、冥想之村、信仰之村——乘船穿行，一湖之上竟有许多个世界。不妨花上几天，悠悠地走一走。" },
        stops:[
          { id:"at1", emoji:"🚤", lat:14.7402, lng:-91.1573,
            title:{ ja:"パナハッチェル（湖の玄関口）", en:"Panajachel (gateway)", es:"Panajachel (la entrada)", zh:"帕纳哈切尔（湖区门户）" },
            narration:{ ja:"湖への玄関口パナハッチェル、通称『パナ』。目抜き通りサンタンデール通りには土産物と食堂が並び、桟橋からは各村行きの乗合ボート（ランチャ）が出る。まずはここで湖の空気とマヤの手工芸に触れよう。", en:"Panajachel — 'Pana' — is the gateway to the lake. Calle Santander is lined with crafts and comedores, and from the docks the shared boats (lanchas) leave for every village. Start here to feel the lake air and browse Maya handicrafts.", es:"Panajachel —'Pana'— es la puerta al lago. La Calle Santander está llena de artesanías y comedores, y desde los muelles salen las lanchas hacia cada pueblo. Empieza aquí para sentir el aire del lago y ver la artesanía maya.", zh:"帕纳哈切尔（人称「Pana」）是通往湖区的门户。桑坦德大街两旁满是手工艺品与小食堂，码头有开往各村的公共小船（lancha）。先在这里感受湖上的空气、逛逛玛雅手工艺吧。" },
            riddle:{ ja:"サンタンデール通りの色とりどりの織物か、桟橋のボートを1枚。", en:"Snap the colorful textiles on Calle Santander, or the boats at the dock.", es:"Fotografía los textiles de colores de la Calle Santander o las lanchas en el muelle.", zh:"拍下桑坦德大街上五彩的织物，或码头边的小船。" } },
          { id:"at2", emoji:"🌅", lat:14.7039, lng:-91.2831,
            title:{ ja:"インディアン・ノーズの日の出（3火山の眺め）", en:"Indian Nose sunrise (three volcanoes)", es:"Amanecer en la Nariz del Indio (tres volcanes)", zh:"印第安人鼻子的日出（三火山之景）" },
            narration:{ ja:"早朝、暗いうちに登る『インディアン・ノーズ（マヤの横顔）』。頂上では、サンペドロ・トリマン・アティトランの3つの火山の向こうから朝日が昇り、湖が黄金色に染まる。アティトラン一番の絶景ポイントだ。", en:"Before dawn you climb the 'Indian Nose' (Rostro Maya). From the top, the sun rises beyond the three volcanoes — San Pedro, Tolimán and Atitlán — and the lake turns gold. It's Atitlán's finest viewpoint.", es:"Antes del amanecer subes a la 'Nariz del Indio' (Rostro Maya). Desde la cima, el sol sale tras los tres volcanes —San Pedro, Tolimán y Atitlán— y el lago se vuelve dorado. Es el mejor mirador de Atitlán.", zh:"天未亮就动身攀登「印第安人的鼻子」（玛雅侧脸山）。登顶后，太阳从圣佩德罗、托利曼、阿蒂特兰三座火山后升起，湖面染成金色。这是阿蒂特兰最美的观景点。" },
            riddle:{ ja:"3つの火山と朝日、湖を1枚に収めよう。", en:"Frame the three volcanoes, the sunrise and the lake in one shot.", es:"Captura los tres volcanes, el amanecer y el lago en una sola foto.", zh:"把三座火山、日出与湖面收进同一张照片。" } },
          { id:"at3", emoji:"🛕", lat:14.6386, lng:-91.2289,
            title:{ ja:"サンティアゴ・アティトラン（マシモン信仰）", en:"Santiago Atitlán (Maximón)", es:"Santiago Atitlán (Maximón)", zh:"圣地亚哥阿蒂特兰（马西蒙信仰）" },
            narration:{ ja:"ツトゥヒル・マヤの町サンティアゴ・アティトラン。ここでは民間信仰の聖人『マシモン（サン・シモン）』が祀られ、葉巻や酒が供えられる。祀られる家は毎年替わるので、地元の子に場所を教えてもらおう。伝統衣装や市場も見応えがある。", en:"Santiago Atitlán is a Tz'utujil Maya town. Here the folk saint 'Maximón (San Simón)' is honored with offerings of cigars and liquor. The house that hosts him changes each year, so ask a local child to guide you. The traditional dress and market are worth seeing too.", es:"Santiago Atitlán es un pueblo maya tz'utujil. Aquí se venera al santo popular 'Maximón (San Simón)' con ofrendas de puros y licor. La casa que lo alberga cambia cada año, así que pide a un niño local que te guíe. El traje tradicional y el mercado también valen la pena.", zh:"圣地亚哥阿蒂特兰是祖图希尔玛雅人的小镇。这里供奉民间圣人「马西蒙（San Simón）」，人们献上雪茄与酒。供奉他的人家每年更换，可请当地孩子带路。传统服饰和市集也很值得一看。" },
            riddle:{ ja:"色鮮やかなツトゥヒルの衣装か、市場の一角を1枚。（マシモンの堂内は撮影可否を必ず確認）", en:"Photograph the vivid Tz'utujil dress or a corner of the market. (Always ask before photographing inside Maximón's shrine.)", es:"Fotografía el vistoso traje tz'utujil o un rincón del mercado. (Pregunta siempre antes de fotografiar dentro del altar de Maximón.)", zh:"拍下鲜艳的祖图希尔服饰，或市集的一角。（在马西蒙神龛内拍照前务必先征得同意。）" } },
          { id:"at4", emoji:"🧵", lat:14.6975, lng:-91.2842,
            title:{ ja:"サンフアン・ラ・ラグーナ（織物と自然染め）", en:"San Juan La Laguna (weaving & natural dyes)", es:"San Juan La Laguna (tejido y tintes)", zh:"圣胡安拉拉古纳（织布与天然染色）" },
            narration:{ ja:"静かなサンフアン・ラ・ラグーナは、織物と自然染めの村。女性の協同組合が、綿を植物や虫の色で染め、腰機で布を織る様子を見せてくれる。坂道の壁画（ムラル）や地元コーヒーもこの村の魅力だ。", en:"Quiet San Juan La Laguna is the village of weaving and natural dyes. Women's cooperatives show how they dye cotton with plants and insects and weave on a backstrap loom. The painted murals up the hill and the local coffee are highlights too.", es:"El tranquilo San Juan La Laguna es el pueblo del tejido y los tintes naturales. Las cooperativas de mujeres muestran cómo tiñen el algodón con plantas e insectos y tejen en telar de cintura. Los murales de la subida y el café local también encantan.", zh:"宁静的圣胡安拉拉古纳是织布与天然染色之村。妇女合作社会向你展示如何用植物和昆虫为棉线染色，并用腰机织布。坡道上的壁画和当地咖啡也是这里的亮点。" },
            riddle:{ ja:"腰機で織る手元か、天然染めの糸のグラデーションを1枚。", en:"Capture hands weaving on the backstrap loom, or the gradient of naturally dyed threads.", es:"Capta las manos tejiendo en el telar de cintura o el degradado de los hilos con tinte natural.", zh:"拍下腰机上织布的双手，或天然染线的渐变色。" } },
          { id:"at5", emoji:"🧘", lat:14.7264, lng:-91.2647,
            title:{ ja:"サンマルコス・ラ・ラグーナ（瞑想と自然保護区）", en:"San Marcos La Laguna (meditation & reserve)", es:"San Marcos La Laguna (meditación y reserva)", zh:"圣马科斯拉拉古纳（冥想与自然保护区）" },
            narration:{ ja:"サンマルコス・ラ・ラグーナは、瞑想やヨガのリトリートが集まるスピリチュアルな村。湖畔の自然保護区セロ・ツァンクヒルには遊歩道と、勇気があれば飛び込める岩場もある。木陰でゆっくり呼吸を整えたい。", en:"San Marcos La Laguna is the spiritual village, full of meditation and yoga retreats. The lakeside Cerro Tzankujil reserve has forest trails and a rock platform for a brave jump into the lake. A place to slow down and breathe under the trees.", es:"San Marcos La Laguna es el pueblo espiritual, lleno de retiros de meditación y yoga. La reserva Cerro Tzankujil, junto al lago, tiene senderos y un peñón para saltar al agua si te atreves. Un lugar para bajar el ritmo y respirar bajo los árboles.", zh:"圣马科斯拉拉古纳是充满冥想与瑜伽静修的灵性小村。湖畔的Cerro Tzankujil自然保护区有林间步道，还有一处岩台，够胆量的话可以跳进湖里。适合在树荫下放慢呼吸。" },
            riddle:{ ja:"木々の間から見える湖か、静かな遊歩道を1枚。", en:"Photograph the lake glimpsed through the trees, or a quiet forest trail.", es:"Fotografía el lago entre los árboles o un sendero tranquilo.", zh:"拍下林间望见的湖，或一条静谧的步道。" } },
          { id:"at6", emoji:"☕", lat:14.6947, lng:-91.2717,
            title:{ ja:"サンペドロ＆湖上ボート（村めぐり・語学）", en:"San Pedro & lake boats (village-hop & Spanish)", es:"San Pedro y las lanchas (recorrido y español)", zh:"圣佩德罗与湖上小船（跳岛游・学西语）" },
            narration:{ ja:"サンペドロ・ラ・ラグーナは語学学校とバックパッカーが集う賑やかな村。カフェで学び、夜は音楽が流れる。そして村から村への移動はすべて湖上のランチャ。水面を切って走る10分の船旅そのものが、アティトランの醍醐味だ。", en:"San Pedro La Laguna is the lively village of language schools and backpackers — study in a cafe, and at night the music flows. And every hop between villages is by lancha across the lake. The ten-minute ride skimming the water is itself the joy of Atitlán.", es:"San Pedro La Laguna es el pueblo animado de las escuelas de español y los mochileros: estudia en un café y de noche suena la música. Y cada salto entre pueblos es en lancha por el lago. Ese viaje de diez minutos rozando el agua es, en sí, el encanto de Atitlán.", zh:"圣佩德罗拉拉古纳是语言学校和背包客云集的热闹小村——在咖啡馆里上课，入夜后乐声流淌。而村与村之间的往来全靠湖上的小船。那贴着水面飞驰的十分钟航程，本身就是阿蒂特兰的乐趣。" },
            riddle:{ ja:"ランチャの舳先から見た湖と火山を1枚。", en:"Shoot the lake and volcanoes from the bow of a lancha.", es:"Fotografía el lago y los volcanes desde la proa de una lancha.", zh:"从小船船头拍下湖面与火山。" } },
        ],
        history:[
          { emoji:"🌋", title:{ ja:"湖はどうやってできた？", en:"How was the lake formed?", es:"¿Cómo se formó el lago?", zh:"湖是怎么形成的？" },
            body:{ ja:"アティトラン湖は、約8万4千年前の巨大噴火でできた巨大なカルデラ（陥没地形）に水がたまったもの。中米で最も深い湖の一つで、水深は300mを超える。周囲にそびえる3つの火山が、その激しい成り立ちを物語る。", en:"Lake Atitlán fills a giant caldera left by a colossal eruption about 84,000 years ago. It's one of the deepest lakes in Central America, over 300 m deep. The three volcanoes around it tell the story of that violent birth.", es:"El lago de Atitlán llena una enorme caldera dejada por una erupción colosal hace unos 84.000 años. Es uno de los lagos más profundos de Centroamérica, con más de 300 m. Los tres volcanes que lo rodean cuentan su nacimiento violento.", zh:"阿蒂特兰湖填满了约8万4千年前一场巨大喷发留下的破火山口（凹陷地形）。它是中美洲最深的湖泊之一，水深超过300米。环湖而立的三座火山，诉说着它剧烈的诞生。" } },
          { emoji:"🧵", title:{ ja:"村ごとに違う民族衣装（ウイピル）", en:"A different huipil for each village", es:"Un huipil distinto por pueblo", zh:"每个村庄不同的民族服饰" },
            body:{ ja:"湖の村々にはツトゥヒル族やカクチケル族が暮らし、女性が着る民族衣装『ウイピル』は村ごとに色や模様が異なる。柄には土地の自然や物語が編み込まれ、どの村の人かひと目で分かる。手に取るなら、ぜひ作り手のいる村で。", en:"The lake villages are home to the Tz'utujil and Kaqchikel peoples, and the women's blouse — the 'huipil' — differs in color and pattern from village to village. The designs weave in local nature and stories, so you can tell someone's village at a glance. If you buy one, buy it where it's made.", es:"En los pueblos del lago viven los tz'utujiles y kaqchikeles, y el 'huipil' de las mujeres cambia de color y diseño según el pueblo. Los patrones tejen la naturaleza y las historias locales; se reconoce el pueblo de un vistazo. Si compras uno, hazlo donde se teje.", zh:"湖畔村庄居住着祖图希尔人和卡克奇克尔人，女性所穿的民族上衣「huipil」在每个村庄颜色与花纹各不相同。图案里编织着当地的自然与故事，一眼便能看出是哪个村的人。若要选购，请到亲手织造的村庄。" } },
          { emoji:"🛕", title:{ ja:"マシモン（サン・シモン）とは？", en:"Who is Maximón (San Simón)?", es:"¿Quién es Maximón (San Simón)?", zh:"马西蒙（San Simón）是谁？" },
            body:{ ja:"マシモンは、マヤの信仰とカトリックが混ざり合って生まれた民間信仰の聖人。葉巻をくわえ、酒やたばこを供物に受け取る、少し破天荒な守り神だ。像を預かる家（コフラディア）は毎年交代し、祭りの日には町を練り歩く。撮影や参拝には敬意を忘れずに。", en:"Maximón is a folk saint born where Maya belief and Catholicism blend — a slightly wild guardian who 'smokes' a cigar and receives offerings of liquor and tobacco. The household that keeps his effigy (the cofradía) rotates each year, and on his feast day he is carried through town. Approach photos and worship with respect.", es:"Maximón es un santo popular nacido de la mezcla de la creencia maya y el catolicismo: un guardián algo indómito que 'fuma' un puro y recibe ofrendas de licor y tabaco. La casa que guarda su imagen (la cofradía) cambia cada año, y en su fiesta lo llevan por el pueblo. Acércate con respeto a las fotos y al culto.", zh:"马西蒙是玛雅信仰与天主教交融而生的民间圣人——一位略显不羁的守护神，口衔雪茄，接受酒与烟草的供奉。保管其神像的人家（cofradía）每年轮换，节庆之日会抬着他巡游全镇。拍照与参拜时请心怀敬意。" } },
        ],
      } },
    { id:"monterrico", order:10, type:"sight", flag:"🇬🇹", lat:13.898, lng:-90.485,
      name:{ ja:"モンテリコ", en:"Monterrico", es:"Monterrico", zh:"蒙特里科" },
      country:{ ja:"グアテマラ", en:"Guatemala", es:"Guatemala", zh:"危地马拉" },
      blurb:{ ja:"黒砂のビーチとウミガメの産卵で知られる太平洋岸の村。", en:"A Pacific-coast village known for black-sand beaches and sea-turtle nesting.", es:"Un pueblo del Pacífico famoso por su playa de arena negra y el desove de tortugas.", zh:"以黑沙海滩和海龟产卵闻名的太平洋岸小镇。" },
      content:{
        intro:{ ja:"首都から車で数時間、太平洋岸の小さな村モンテリコ。黒い砂のビーチ、ウミガメの保護と放流、マングローブの運河めぐり、そして息をのむ夕日。のんびりとした空気の中で、自然と命の営みに出会う1〜2日を。", en:"A few hours from the capital, Monterrico is a small Pacific-coast village: black-sand beaches, sea-turtle conservation and hatchling releases, mangrove-canal tours, and breathtaking sunsets. Come for a slow day or two among nature and the rhythm of life.", es:"A pocas horas de la capital, Monterrico es un pueblo del Pacífico: playas de arena negra, conservación y suelta de tortugas, paseos por el canal de manglares y atardeceres de ensueño. Ven uno o dos días de calma entre la naturaleza y el pulso de la vida.", zh:"距首都数小时车程，蒙特里科是太平洋岸的小村：黑沙海滩、海龟保护与放流、红树林运河之旅，还有令人屏息的夕阳。来这里悠悠地待上一两天，遇见自然与生命的律动。" },
        stops:[
          { id:"mn1", emoji:"🖤", lat:13.8918, lng:-90.4808,
            title:{ ja:"黒砂のビーチ", en:"Black-sand beach", es:"Playa de arena negra", zh:"黑沙海滩" },
            narration:{ ja:"モンテリコの第一印象は、足の裏に広がる黒い砂。近くの火山が生んだ砂で、晴れた日中は驚くほど熱くなる。目の前の太平洋は波が高くダイナミック。まずはこの黒いビーチと大波を眺めてみよう。", en:"Monterrico's first surprise is the jet-black sand under your feet — born from nearby volcanoes and scorching on a sunny afternoon. In front of you the Pacific rolls in with big, powerful waves. Take a moment to feel this black beach and its restless surf.", es:"La primera sorpresa de Monterrico es la arena negra bajo tus pies, nacida de los volcanes cercanos y ardiente al mediodía. Frente a ti, el Pacífico rompe con olas grandes y potentes. Tómate un momento para sentir esta playa negra y su oleaje.", zh:"蒙特里科给你的第一印象，是脚下那片乌黑的沙滩——它源自附近的火山，晴天午后会烫得惊人。眼前的太平洋涌来一波波高大有力的浪。先驻足感受这片黑沙滩与不息的海浪吧。" },
            riddle:{ ja:"黒い砂に残る足あとか、打ち寄せる大波を1枚撮ろう。", en:"Photograph your footprints in the black sand, or a big wave rolling in.", es:"Fotografía tus huellas en la arena negra o una gran ola rompiendo.", zh:"拍下你留在黑沙上的脚印，或一朵扑岸的大浪。" } },
          { id:"mn2", emoji:"🐢", lat:13.8946, lng:-90.4842,
            title:{ ja:"ウミガメ保護センター（トルトゥガリオ）", en:"Sea-turtle hatchery (El Tortugario)", es:"Vivero de tortugas (El Tortugario)", zh:"海龟保护中心（Tortugario）" },
            narration:{ ja:"村の一角にあるウミガメ保護センター『エル・トルトゥガリオ』。ここではパルラマ（ヒメウミガメ）などの卵を安全に孵化させ、赤ちゃんガメを海に返している。夕方には旅行者も放流に参加できる日がある。命をつなぐ現場をのぞいてみよう。", en:"Tucked in the village is El Tortugario, a sea-turtle hatchery. Here the eggs of the parlama (olive ridley) and other turtles are hatched safely and the hatchlings released to the sea. At dusk, visitors can sometimes join a release. Step in and see conservation in action.", es:"En el pueblo está El Tortugario, un vivero de tortugas marinas. Aquí incuban los huevos de la parlama (tortuga golfina) y liberan a las crías al mar. Al atardecer, a veces los viajeros participan en una suelta. Asómate a ver la conservación en acción.", zh:"村里一角有座海龟保护中心「El Tortugario」。这里把帕拉玛（丽龟）等海龟的卵安全孵化，再把小海龟放归大海。傍晚有时游客也能参加放流。进去看看守护生命的现场吧。" },
            riddle:{ ja:"手のひらサイズの赤ちゃんガメが海へ向かう瞬間を撮ろう（放流に参加できたら）。", en:"Capture a palm-sized hatchling heading for the sea (if you join a release).", es:"Capta una cría del tamaño de tu palma rumbo al mar (si participas en una suelta).", zh:"拍下巴掌大的小海龟奔向大海的瞬间（若能参加放流）。" } },
          { id:"mn3", emoji:"🌅", lat:13.8920, lng:-90.4820,
            title:{ ja:"太平洋のサンセット", en:"Pacific sunset", es:"Atardecer del Pacífico", zh:"太平洋日落" },
            narration:{ ja:"モンテリコといえば、太平洋に沈む夕日。水平線がオレンジから紫へと染まる時間は格別だ。多くのウミガメ放流もこの夕暮れに行われる。波打ち際に立って、1日の終わりをゆっくり味わおう。", en:"Monterrico is famous for its Pacific sunset. As the horizon shifts from orange to purple, the whole beach glows. Many turtle releases happen at this hour. Stand at the water's edge and let the day wind down.", es:"Monterrico es famoso por su atardecer sobre el Pacífico. Cuando el horizonte pasa del naranja al morado, toda la playa brilla. Muchas sueltas de tortugas ocurren a esta hora. Párate en la orilla y despide el día.", zh:"说到蒙特里科，就是那轮沉入太平洋的夕阳。地平线由橙转紫的时刻格外动人，许多海龟放流也在此时进行。站到海水边，慢慢送别这一天吧。" },
            riddle:{ ja:"水平線に沈む夕日のシルエットを1枚。", en:"One silhouette shot of the sun sinking into the horizon.", es:"Una silueta del sol hundiéndose en el horizonte.", zh:"拍一张夕阳沉入地平线的剪影。" } },
          { id:"mn4", emoji:"🛶", lat:13.9048, lng:-90.4925,
            title:{ ja:"チキムリージャ運河（マングローブ）", en:"Chiquimulilla Canal (mangroves)", es:"Canal de Chiquimulilla (manglares)", zh:"奇基穆利利亚运河（红树林）" },
            narration:{ ja:"村の裏手には、海と並行して伸びるチキムリージャ運河が広がる。早朝、小舟でマングローブの林を進めば、サギやカワセミ、運が良ければイグアナやワニに出会える。エンジンを止めた静けさが心地よい。", en:"Behind the village runs the Chiquimulilla Canal, a maze of mangroves parallel to the sea. Take a small boat at dawn and glide through the mangrove forest — herons, kingfishers, and with luck iguanas or caimans appear. The stillness when the engine cuts is magical.", es:"Detrás del pueblo corre el Canal de Chiquimulilla, un laberinto de manglares paralelo al mar. Sal en lancha al amanecer y navega entre los manglares: garzas, martines pescadores y, con suerte, iguanas o caimanes. El silencio al apagar el motor es mágico.", zh:"村子背后是与海平行延伸的奇基穆利利亚运河。清晨乘小船穿行红树林，能看到白鹭、翠鸟，运气好还能遇见鬣蜥或凯门鳄。熄灭马达后的宁静格外迷人。" },
            riddle:{ ja:"小舟から見上げるマングローブのトンネルを撮ろう。", en:"Shoot the mangrove tunnel as seen from your boat.", es:"Fotografía el túnel de manglares visto desde tu lancha.", zh:"从小船上拍下红树林拱成的绿色隧道。" } },
          { id:"mn5", emoji:"🐟", lat:13.8952, lng:-90.4830,
            title:{ ja:"海辺の食堂・海の幸", en:"Seaside comedor", es:"Comedor junto al mar", zh:"海边小食堂" },
            narration:{ ja:"遊んだあとは海辺の食堂へ。獲れたての魚のフライ（pescado frito）やセビーチェ、冷たい一杯が定番だ。素足のまま砂の上で食べる海の幸は格別。地元の人にその日のおすすめを聞いてみよう。", en:"After the beach, head to a seaside comedor. Fresh fried fish (pescado frito), ceviche, and a cold drink are the classics. Eating seafood barefoot on the sand hits differently. Ask a local for today's catch.", es:"Después de la playa, ve a un comedor junto al mar. Pescado frito, ceviche y una bebida fría son lo clásico. Comer mariscos descalzo sobre la arena sabe distinto. Pregunta a un local por la pesca del día.", zh:"玩累了就去海边的小食堂。现炸鲜鱼（pescado frito）、酸橘汁腌鱼（ceviche）配一杯冰饮是经典。赤脚坐在沙上吃海鲜别有风味。问问当地人今天有什么好货。" },
            riddle:{ ja:"テーブルに並んだ海の幸を、いただく前に1枚。", en:"Snap your seafood plate before the first bite.", es:"Foto de tu plato de mariscos antes del primer bocado.", zh:"开动之前，给你那盘海鲜拍一张。" } },
        ],
        history:[
          { emoji:"🌋", title:{ ja:"なぜ砂が黒いの？", en:"Why is the sand black?", es:"¿Por qué la arena es negra?", zh:"沙子为什么是黑的？" },
            body:{ ja:"モンテリコの黒い砂は、内陸の火山から生まれたもの。火山岩が砕けて川に運ばれ、太平洋岸にたどり着いた。だから鉄分を含み、日中は素足で歩けないほど熱くなる。", en:"Monterrico's black sand comes from inland volcanoes. Volcanic rock breaks down, rivers carry it to the Pacific coast, and it gathers here — mineral-rich and so hot at midday you can't walk barefoot.", es:"La arena negra de Monterrico viene de los volcanes del interior. La roca volcánica se erosiona, los ríos la llevan al Pacífico y se acumula aquí: rica en minerales y tan caliente al mediodía que no puedes caminar descalzo.", zh:"蒙特里科的黑沙来自内陆的火山。火山岩风化后被河流带到太平洋岸并在此堆积，富含矿物，正午时烫得无法赤脚行走。" } },
          { emoji:"🐢", title:{ ja:"パルラマ（ウミガメ）を守る", en:"Protecting the parlama", es:"Proteger a la parlama", zh:"守护帕拉玛海龟" },
            body:{ ja:"7〜12月ごろ、ヒメウミガメ（現地名パルラマ）が夜の砂浜に産卵に来る。地域では、採った卵の一部を保護センターに寄付する仕組みで孵化を支えている。より希少なオサガメ（バウレ）もこの海岸に上がる。", en:"From about July to December, olive ridley turtles (locally 'parlama') come ashore at night to nest. The community supports hatching by donating a share of collected eggs to the hatchery. The rarer leatherback ('baule') also nests on this coast.", es:"De julio a diciembre, la tortuga golfina ('parlama') sube de noche a anidar. La comunidad apoya la incubación donando parte de los huevos recolectados al tortugario. La más rara tortuga baule (laúd) también anida en esta costa.", zh:"约7至12月，丽龟（当地称「帕拉玛」）会在夜里上岸产卵。社区通过把采集到的部分龟卵捐给保护中心来支持孵化。更为稀有的棱皮龟（baule）也会到这片海岸产卵。" } },
          { emoji:"🌊", title:{ ja:"波が強い理由と安全", en:"Big waves & safety", es:"Olas fuertes y seguridad", zh:"浪大与安全" },
            body:{ ja:"モンテリコの浜は急に深くなり、太平洋のうねりも大きいため、引き波（リップカレント）が強い。美しいが遊泳は油断禁物。腰より深く入らない、子どもから目を離さない、地元の助言に従うのが安心だ。", en:"Monterrico's beach drops off steeply and faces the open Pacific, so rip currents are strong. It's beautiful but not for careless swimming. Stay no deeper than your waist, watch children closely, and follow local advice.", es:"La playa de Monterrico se hace honda de golpe y da al Pacífico abierto, así que las corrientes de resaca son fuertes. Es bella pero no para nadar sin cuidado. No pases de la cintura, vigila a los niños y sigue los consejos locales.", zh:"蒙特里科的海滩骤然变深，又正对开阔的太平洋，因此离岸流很强。虽美却不宜大意游泳。下水别超过腰部、看好孩子、听从当地人的建议才安心。" } },
        ],
      } },
  ],

  // 国リスト（出身国・誇りに思う国 用。flag＋多言語名）
  countries: [
    {c:"JP",f:"🇯🇵",ja:"日本",en:"Japan",es:"Japón"},
    {c:"GT",f:"🇬🇹",ja:"グアテマラ",en:"Guatemala",es:"Guatemala"},
    {c:"US",f:"🇺🇸",ja:"アメリカ",en:"USA",es:"Estados Unidos"},
    {c:"CA",f:"🇨🇦",ja:"カナダ",en:"Canada",es:"Canadá"},
    {c:"MX",f:"🇲🇽",ja:"メキシコ",en:"Mexico",es:"México"},
    {c:"ES",f:"🇪🇸",ja:"スペイン",en:"Spain",es:"España"},
    {c:"FR",f:"🇫🇷",ja:"フランス",en:"France",es:"Francia"},
    {c:"DE",f:"🇩🇪",ja:"ドイツ",en:"Germany",es:"Alemania"},
    {c:"GB",f:"🇬🇧",ja:"イギリス",en:"UK",es:"Reino Unido"},
    {c:"IT",f:"🇮🇹",ja:"イタリア",en:"Italy",es:"Italia"},
    {c:"NL",f:"🇳🇱",ja:"オランダ",en:"Netherlands",es:"Países Bajos"},
    {c:"CH",f:"🇨🇭",ja:"スイス",en:"Switzerland",es:"Suiza"},
    {c:"PT",f:"🇵🇹",ja:"ポルトガル",en:"Portugal",es:"Portugal"},
    {c:"IE",f:"🇮🇪",ja:"アイルランド",en:"Ireland",es:"Irlanda"},
    {c:"SE",f:"🇸🇪",ja:"スウェーデン",en:"Sweden",es:"Suecia"},
    {c:"NO",f:"🇳🇴",ja:"ノルウェー",en:"Norway",es:"Noruega"},
    {c:"AU",f:"🇦🇺",ja:"オーストラリア",en:"Australia",es:"Australia"},
    {c:"NZ",f:"🇳🇿",ja:"ニュージーランド",en:"New Zealand",es:"Nueva Zelanda"},
    {c:"BR",f:"🇧🇷",ja:"ブラジル",en:"Brazil",es:"Brasil"},
    {c:"AR",f:"🇦🇷",ja:"アルゼンチン",en:"Argentina",es:"Argentina"},
    {c:"CL",f:"🇨🇱",ja:"チリ",en:"Chile",es:"Chile"},
    {c:"CO",f:"🇨🇴",ja:"コロンビア",en:"Colombia",es:"Colombia"},
    {c:"PE",f:"🇵🇪",ja:"ペルー",en:"Peru",es:"Perú"},
    {c:"CR",f:"🇨🇷",ja:"コスタリカ",en:"Costa Rica",es:"Costa Rica"},
    {c:"SV",f:"🇸🇻",ja:"エルサルバドル",en:"El Salvador",es:"El Salvador"},
    {c:"HN",f:"🇭🇳",ja:"ホンジュラス",en:"Honduras",es:"Honduras"},
    {c:"NI",f:"🇳🇮",ja:"ニカラグア",en:"Nicaragua",es:"Nicaragua"},
    {c:"BZ",f:"🇧🇿",ja:"ベリーズ",en:"Belize",es:"Belice"},
    {c:"KR",f:"🇰🇷",ja:"韓国",en:"Korea",es:"Corea"},
    {c:"CN",f:"🇨🇳",ja:"中国",en:"China",es:"China"},
    {c:"TW",f:"🇹🇼",ja:"台湾",en:"Taiwan",es:"Taiwán"},
    {c:"TH",f:"🇹🇭",ja:"タイ",en:"Thailand",es:"Tailandia"},
    {c:"IN",f:"🇮🇳",ja:"インド",en:"India",es:"India"},
    {c:"IL",f:"🇮🇱",ja:"イスラエル",en:"Israel",es:"Israel"},
    {c:"ZA",f:"🇿🇦",ja:"南アフリカ",en:"South Africa",es:"Sudáfrica"},
    {c:"PL",f:"🇵🇱",ja:"ポーランド",en:"Poland",es:"Polonia"},
  ],
};
