// Mi Amigo — 多言語データ（日本語 / English / Español）
// 写真は img フィールドに "img/<id>.jpg" or 画像URL。未指定は emoji プレースホルダー。
// 価格(price)は USD のおおよその目安。
window.MI_AMIGO_DATA = {
  listings: [
    { id:"delagente-coffee", type:"exp", emoji:"☕", price:40, unit:"USD", maxSlots:8,
      area:"San Miguel Escobar（アンティグア近郊）", link:"https://www.delagente.org/", img:"",
      title:{ ja:"De La Gente コーヒー農園＆コミュニティ体験", en:"De La Gente Coffee Farm & Community Tour", es:"Finca de café y comunidad De La Gente" },
      desc:{ ja:"生産者協同組合と歩く社会的企業のツアー。摘み取り〜焙煎、コミュニティ支援の現場まで",
             en:"A social-enterprise tour with farmer cooperatives: from picking to roasting, and the community behind it.",
             es:"Un tour de empresa social con cooperativas: de la cosecha al tueste, y la comunidad detrás." } },
    { id:"chocomuseo-bar", type:"exp", emoji:"🍫", price:33, unit:"USD", maxSlots:12,
      area:"4a calle oriente", link:"https://www.chocomuseo.com/", img:"",
      title:{ ja:"ChocoMuseo Bean-to-Bar チョコ ワークショップ", en:"ChocoMuseo Bean-to-Bar Chocolate Workshop", es:"Taller de chocolate Bean-to-Bar ChocoMuseo" },
      desc:{ ja:"カカオ豆から板チョコまで（約2時間）。手作り120gをお持ち帰り",
             en:"From cacao bean to bar (about 2 hours). Take home 120g you made yourself.",
             es:"Del grano de cacao a la barra (unas 2 horas). Llévate 120g hechos por ti." } },
    { id:"kakaw-weaving", type:"exp", emoji:"🧵", price:45, unit:"USD", maxSlots:5,
      area:"アンティグア中心部 / Antigua centro", link:"https://kakawdesigns.com/", img:"",
      title:{ ja:"Kakaw Designs バックストラップ織り ワークショップ", en:"Kakaw Designs Backstrap Weaving Workshop", es:"Taller de telar de cintura Kakaw Designs" },
      desc:{ ja:"マヤの腰機織りを庭で学ぶ（英・西対応）。福祉×ウイピル アップサイクルと連動",
             en:"Learn Maya backstrap weaving in a garden (EN/ES). Linked to our huipil upcycling project.",
             es:"Aprende el telar de cintura maya en un jardín (EN/ES). Ligado a nuestro proyecto de huipil." } },
    { id:"food-tour", type:"exp", emoji:"🥘", price:55, unit:"USD", maxSlots:10,
      area:"アンティグア旧市街 / Antigua casco", link:"", img:"",
      title:{ ja:"アンティグア ストリートフード ツアー", en:"Antigua Street Food Tour", es:"Tour de comida callejera de Antigua" },
      desc:{ ja:"ガイドと市場〜名店を巡り約10品を試食。少人数制",
             en:"Taste about 10 dishes from market to favorite spots with a guide. Small groups.",
             es:"Prueba unos 10 platillos del mercado a los mejores lugares con un guía. Grupos pequeños." } },
    { id:"kombu-ramen", type:"food", emoji:"🍜", price:14, unit:"USD", maxSlots:16,
      area:"3a calle oriente #19D", link:"https://komburamenshop.com/", img:"",
      title:{ ja:"Kombu Ramen Shop 席予約", en:"Kombu Ramen Shop Reservation", es:"Reserva en Kombu Ramen Shop" },
      desc:{ ja:"グアテマラ初のラーメン店。地元産小麦の自家製麺と6種のラーメン",
             en:"Guatemala's first ramen shop. House-made noodles from local flour, 6 kinds of ramen.",
             es:"El primer ramen de Guatemala. Fideos caseros de harina local y 6 tipos de ramen." } },
    { id:"barbara-hostel", type:"stay", emoji:"🛏️", price:15, unit:"USD", maxSlots:10,
      area:"アンティグア中心部 / Antigua centro", link:"", img:"",
      title:{ ja:"Barbara's Boutique Hostel（1泊・ドミトリー）", en:"Barbara's Boutique Hostel (dorm, 1 night)", es:"Barbara's Boutique Hostel (dormitorio, 1 noche)" },
      desc:{ ja:"コロニアル様式の邸宅。屋上テラスからアグア・フエゴ・アカテナンゴの3火山",
             en:"A colonial house with a rooftop overlooking the Agua, Fuego and Acatenango volcanoes.",
             es:"Una casa colonial con azotea y vista a los volcanes Agua, Fuego y Acatenango." } },
  ],

  // 謎解きの全体情報（謎は下の guide.route.stops から生成）
  quest: {
    title:  { ja:"アンティグア 歴史ミステリー・ラリー", en:"Antigua History Mystery Rally", es:"Rally del misterio histórico de Antigua" },
    reward: { ja:"7/10クリアで次のダンジョン（次の世界遺産）が出現！", en:"Clear 7/10 to make the next dungeon (heritage site) appear!", es:"¡Completa 7/10 para que aparezca la próxima mazmorra (sitio del patrimonio)!" },
  },

  // 音声ウォーキングガイド ＝ 謎解きスポット（多言語）
  guide: {
    route: {
      title: { ja:"アンティグア 街歩き音声ガイド", en:"Antigua Walking Audio Guide", es:"Audioguía a pie de Antigua" },
      intro: {
        ja:"世界遺産の街アンティグアを約10スポット巡ります。再生すると物語が流れ、謎解きでは“その場所”の写真を撮って投稿します。",
        en:"Walk the UNESCO city of Antigua across ~10 stops. Play to hear each story; in the rally, photograph the place and post it.",
        es:"Recorre la ciudad Patrimonio de Antigua en ~10 paradas. Reproduce para oír la historia; en el rally, fotografía el lugar y publícalo.",
      },
      stops: [
        { id:"s1", emoji:"🌉", lat:14.5586, lng:-90.7339,
          title:{ ja:"サンタ・カタリナのアーチ", en:"Santa Catalina Arch", es:"Arco de Santa Catalina" },
          text:{ ja:"アンティグアの象徴、黄色いアーチ。17世紀、修道女たちが通りに姿を見せず行き来できるよう、修道院と学校をつなぐ橋として造られました。背後にはアグア火山がそびえます。",
                 en:"Antigua's icon, the yellow arch. Built in the 17th century so cloistered nuns could cross the street unseen, linking the convent and school. Volcán de Agua rises behind it.",
                 es:"El ícono de Antigua, el arco amarillo. Construido en el siglo XVII para que las monjas de clausura cruzaran la calle sin ser vistas. Detrás se alza el Volcán de Agua." },
          riddle:{ ja:"修道女たちが人目を避けて通りを渡れるよう造られた『黄色いアーチ』。その姿を写真に撮ろう。",
                   en:"Find the yellow arch built so cloistered nuns could cross the street unseen. Photograph it.",
                   es:"Encuentra el arco amarillo hecho para que las monjas cruzaran sin ser vistas. Fotografíalo." } },
        { id:"s2", emoji:"⛲", lat:14.5564, lng:-90.7339,
          title:{ ja:"中央公園（プラサ・マヨール）", en:"Central Park (Plaza Mayor)", es:"Parque Central (Plaza Mayor)" },
          text:{ ja:"街の心臓部。中央には「人魚の噴水」が立ち、大聖堂や旧総督府に囲まれています。人々が集い、休む、アンティグアの暮らしの中心です。",
                 en:"The heart of the city. At its center stands the Fountain of the Sirens, surrounded by the cathedral and old palaces.",
                 es:"El corazón de la ciudad. En su centro está la Fuente de las Sirenas, rodeada por la catedral y los palacios." },
          riddle:{ ja:"街の中心、『人魚の噴水』が立つ広場。噴水を写真に撮ろう。",
                   en:"The central plaza with the Fountain of the Sirens. Photograph the fountain.",
                   es:"La plaza central con la Fuente de las Sirenas. Fotografía la fuente." } },
        { id:"s3", emoji:"⛪", lat:14.5566, lng:-90.7327,
          title:{ ja:"サン・ホセ大聖堂（旧聖堂跡）", en:"Cathedral of San José (ruins)", es:"Catedral de San José (ruinas)" },
          text:{ ja:"かつて中米最大級を誇った聖堂。1773年の大地震で崩れ、今もその壮大な廃墟が残ります。",
                 en:"Once among the grandest cathedrals in Central America, toppled by the 1773 earthquake. Its majestic ruins still stand.",
                 es:"Una de las catedrales más grandiosas de Centroamérica, derribada por el terremoto de 1773. Sus ruinas aún se alzan." },
          riddle:{ ja:"1773年の地震で崩れた、かつて中米最大級の聖堂跡。その廃墟を写真に撮ろう。",
                   en:"The ruins of what was one of Central America's grandest cathedrals, felled in 1773. Photograph them.",
                   es:"Las ruinas de una de las mayores catedrales, caída en 1773. Fotografíalas." } },
        { id:"s4", emoji:"🏛️", lat:14.5560, lng:-90.7335,
          title:{ ja:"総督府（カピタネス・ヘネラレス宮殿）", en:"Palace of the Captains General", es:"Palacio de los Capitanes Generales" },
          text:{ ja:"スペイン植民地時代、グアテマラ総督領を治めた政庁。長く連なるアーチの回廊が当時の権力を物語ります。",
                 en:"The seat of Spanish colonial government. Its long arcade of arches speaks to the reach of that power.",
                 es:"La sede del gobierno colonial español. Su larga arcada habla del alcance de aquel poder." },
          riddle:{ ja:"長いアーチの回廊が続く、植民地時代の総督府。その回廊を写真に撮ろう。",
                   en:"The colonial palace with a long arcade of arches. Photograph the arcade.",
                   es:"El palacio colonial con una larga arcada. Fotografía la arcada." } },
        { id:"s5", emoji:"💛", lat:14.5601, lng:-90.7344,
          title:{ ja:"ラ・メルセー教会", en:"La Merced Church", es:"Iglesia de La Merced" },
          text:{ ja:"鮮やかな黄色と白の漆喰装飾が美しいバロック教会。地震に耐えるよう低く頑丈に設計されました。",
                 en:"A Baroque church famed for its vivid yellow facade and white stucco, built low and strong to resist earthquakes.",
                 es:"Una iglesia barroca célebre por su fachada amarilla y estuco blanco, baja y fuerte contra terremotos." },
          riddle:{ ja:"鮮やかな黄色のバロック教会。その正面（ファサード）を写真に撮ろう。",
                   en:"The vivid yellow Baroque church. Photograph its facade.",
                   es:"La iglesia barroca amarilla. Fotografía su fachada." } },
        { id:"s6", emoji:"🏚️", lat:14.5588, lng:-90.7316,
          title:{ ja:"カプチナス修道院", en:"Las Capuchinas Convent", es:"Convento de las Capuchinas" },
          text:{ ja:"保存状態の良い修道院。円形に並ぶ修道女の小部屋「塔」が珍しく、静寂と祈りの暮らしを今に伝えます。",
                 en:"A well-preserved convent. Its unusual circular 'tower' of nuns' cells conveys a life of silence and prayer.",
                 es:"Un convento bien conservado. Su singular 'torre' circular de celdas evoca el silencio y la oración." },
          riddle:{ ja:"円形に小部屋が並ぶ珍しい修道院。その中庭か塔を写真に撮ろう。",
                   en:"The convent with an unusual circular tower of cells. Photograph the courtyard or tower.",
                   es:"El convento con una torre circular de celdas. Fotografía el patio o la torre." } },
        { id:"s7", emoji:"✝️", lat:14.5650, lng:-90.7300,
          title:{ ja:"クルスの丘（展望台）", en:"Hill of the Cross (viewpoint)", es:"Cerro de la Cruz (mirador)" },
          text:{ ja:"街を見下ろす丘の上の十字架。アンティグアの碁盤の街並みと、その先のアグア火山が一直線に並ぶ絶景です。",
                 en:"A cross on the hill above the city, where Antigua's grid lines up with Volcán de Agua beyond.",
                 es:"Una cruz sobre la colina, donde la cuadrícula de Antigua se alinea con el Volcán de Agua." },
          riddle:{ ja:"丘の上の十字架から、街とアグア火山が一直線に見える展望。その景色を写真に撮ろう。",
                   en:"The hilltop cross where city and Volcán de Agua align. Photograph the view.",
                   es:"La cruz en la colina donde la ciudad y el volcán se alinean. Fotografía la vista." } },
        { id:"s8", emoji:"🙏", lat:14.5535, lng:-90.7313,
          title:{ ja:"サン・フランシスコ教会（エルマノ・ペドロ）", en:"San Francisco Church (Hermano Pedro)", es:"Iglesia de San Francisco (Hermano Pedro)" },
          text:{ ja:"中米初の聖人、エルマノ・ペドロが眠る巡礼地。今も多くの人が願いを胸に祈りを捧げます。",
                 en:"A pilgrimage site holding the tomb of Hermano Pedro, the first saint of Central America.",
                 es:"Un sitio de peregrinación con la tumba del Hermano Pedro, el primer santo de Centroamérica." },
          riddle:{ ja:"中米初の聖人エルマノ・ペドロが眠る教会。その外観を写真に撮ろう。",
                   en:"The church holding the tomb of Hermano Pedro, the first saint. Photograph its exterior.",
                   es:"La iglesia con la tumba del Hermano Pedro. Fotografía su exterior." } },
        { id:"s9", emoji:"💧", lat:14.5560, lng:-90.7300,
          title:{ ja:"タンケ・ラ・ウニオン（洗濯場）", en:"Tanque La Unión (wash basins)", es:"Tanque La Unión (lavaderos)" },
          text:{ ja:"石造りの公共洗濯場。植民地時代から人々が洗濯や語らいに集った場所で、今も地元の暮らしが息づいています。",
                 en:"Public stone wash basins where people have gathered to wash and talk since colonial times.",
                 es:"Lavaderos públicos de piedra donde la gente se reúne a lavar y conversar desde la colonia." },
          riddle:{ ja:"今も使われる石造りの公共洗濯場。その水場を写真に撮ろう。",
                   en:"The stone public wash basins still in use today. Photograph them.",
                   es:"Los lavaderos públicos de piedra aún en uso. Fotografíalos." } },
        { id:"s10", emoji:"🧶", lat:14.5558, lng:-90.7352,
          title:{ ja:"工芸市場（ウイピルの織物）", en:"Crafts Market (Huipil textiles)", es:"Mercado de Artesanías (huipiles)" },
          text:{ ja:"色鮮やかなマヤの織物「ウイピル」が並ぶ市場。一枚一枚が村ごとの模様を持ち、作り手の物語を宿しています。",
                 en:"A market bright with Maya 'huipil' textiles, each carrying the pattern of its village.",
                 es:"Un mercado lleno de textiles mayas 'huipiles', cada uno con el patrón de su pueblo." },
          riddle:{ ja:"色鮮やかなウイピルが並ぶ工芸市場。お気に入りの織物を写真に撮ろう。",
                   en:"The crafts market full of colorful huipiles. Photograph your favorite textile.",
                   es:"El mercado de artesanías lleno de huipiles. Fotografía tu textil favorito." } },
      ],
    },
    // 歴史を聴くシリーズ（場所に縛られない音声）
    history: [
      { id:"h1", emoji:"📜",
        title:{ ja:"グアテマラ小史", en:"A Short History of Guatemala", es:"Breve historia de Guatemala" },
        text:{ ja:"マヤ文明の地に、1524年スペインのアルバラードが征服者として現れ、植民地時代が始まりました。1821年に独立。先住民の文化と植民の歴史が、今のグアテマラに重なっています。",
               en:"On the land of the Maya, the Spaniard Alvarado arrived as conqueror in 1524, beginning the colonial era. Independence came in 1821.",
               es:"En tierra maya, el español Alvarado llegó como conquistador en 1524, iniciando la época colonial. La independencia llegó en 1821." } },
      { id:"h2", emoji:"🌋",
        title:{ ja:"アンティグア、遷都の物語", en:"Antigua: Why the Capital Moved", es:"Antigua: por qué se mudó la capital" },
        text:{ ja:"この街はかつて「サンティアゴ・デ・ロス・カバジェロス」という首都でした。1773年のサンタ・マルタ大地震で甚大な被害を受け、首都は現在のグアテマラシティへ移転。残されたこの街は「ラ・アンティグア（古い都）」と呼ばれるようになりました。",
               en:"This city was once the capital, 'Santiago de los Caballeros.' The 1773 earthquakes devastated it, the capital moved to today's Guatemala City, and what remained became 'La Antigua'.",
               es:"Esta ciudad fue la capital, 'Santiago de los Caballeros'. Los terremotos de 1773 la devastaron, la capital se trasladó y lo que quedó se llamó 'La Antigua'." } },
    ],
  },

  // なかま（コミュニティ）— デモのグループとメッセージ（ワールドホステル風）
  community: {
    groups: [
      { id:"g-tour", emoji:"🏛️", name:{ ja:"アンティグア世界遺産ツアー", en:"Antigua Heritage Tour", es:"Tour Patrimonio de Antigua" },
        seed:[
          { from:"Lucía", emoji:"🦜", text:"¡Hola amigos! ¿Alguien sube al Cerro de la Cruz al atardecer? 🌋" },
          { from:"Ken", emoji:"🎒", text:"行きたい！何時集合？" },
          { from:"Mia", emoji:"📷", text:"Just got the yellow arch shot, it's glowing today ✨" },
        ] },
      { id:"g-cafe", emoji:"☕", name:{ ja:"カフェ好き Amigos", en:"Café Amigos", es:"Amigos del café" },
        seed:[
          { from:"Sofía", emoji:"☕", text:"Fat Cat tiene el mejor cortado 👌" },
          { from:"Tomo", emoji:"🍰", text:"12 Onzas のケーキ最高だった！" },
        ] },
      { id:"g-lounge", emoji:"🌏", name:{ ja:"旅人ラウンジ", en:"Traveler Lounge", es:"Sala de viajeros" },
        seed:[
          { from:"Diego", emoji:"🎸", text:"Live music at the hostel tonight, todos invitados!" },
          { from:"Anna", emoji:"🌻", text:"Anyone heading to Lake Atitlán this weekend?" },
        ] },
    ],
  },

  // 世界遺産ステージ（地球儀ピン）。order順に解禁。questSource="antigua"はguide.route.stopsを謎解きに使う。
  // 第1ステージ=アンティグアのみコンテンツ実装済み。以降は near-future（コンテンツ近日）。
  stages: [
    { id:"antigua", order:1, questSource:"antigua", flag:"🇬🇹", lat:14.557, lng:-90.733,
      name:{ ja:"アンティグア・グアテマラ", en:"Antigua Guatemala", es:"Antigua Guatemala" },
      country:{ ja:"グアテマラ", en:"Guatemala", es:"Guatemala" } },
    { id:"tikal", order:2, flag:"🇬🇹", lat:17.222, lng:-89.623,
      name:{ ja:"ティカル遺跡", en:"Tikal", es:"Tikal" },
      country:{ ja:"グアテマラ", en:"Guatemala", es:"Guatemala" } },
    { id:"copan", order:3, flag:"🇭🇳", lat:14.838, lng:-89.142,
      name:{ ja:"コパンのマヤ遺跡", en:"Copán", es:"Copán" },
      country:{ ja:"ホンジュラス", en:"Honduras", es:"Honduras" } },
    { id:"chichen", order:4, flag:"🇲🇽", lat:20.683, lng:-88.568,
      name:{ ja:"チチェン・イッツァ", en:"Chichén Itzá", es:"Chichén Itzá" },
      country:{ ja:"メキシコ", en:"Mexico", es:"México" } },
    { id:"machupicchu", order:5, flag:"🇵🇪", lat:-13.163, lng:-72.545,
      name:{ ja:"マチュ・ピチュ", en:"Machu Picchu", es:"Machu Picchu" },
      country:{ ja:"ペルー", en:"Peru", es:"Perú" },
      content:{
        intro:{ ja:"標高2,430m、雲の上に築かれた15世紀インカ帝国の聖なる都市。段々畑と精巧な石組みが今も息づく『空中都市』。", en:"A sacred 15th-century Inca city built above the clouds at 2,430m — the 'city in the sky', with living terraces and masterful stonework.", es:"Ciudad sagrada inca del siglo XV sobre las nubes a 2.430 m — la 'ciudad en el cielo', con andenes y cantería magistral." },
        stops:[
          { id:"mp1", emoji:"🌅", lat:-13.1730, lng:-72.5409,
            title:{ ja:"太陽の門（インティ・プンク）", en:"Sun Gate (Inti Punku)", es:"Puerta del Sol (Inti Punku)" },
            narration:{ ja:"インカ道から遺跡へ入る石の門。夏至の朝、ここから昇る太陽が街を照らすように設計された。", en:"The stone gateway where the Inca Trail enters the site. At the solstice, the rising sun was designed to light the city from here.", es:"La puerta de piedra donde el Camino Inca entra al sitio. En el solsticio, el sol naciente iluminaba la ciudad desde aquí." },
            riddle:{ ja:"朝もやの中、遺跡全体が初めて見える石の門。そこからの絶景を撮ろう。", en:"The stone gate where you first see the whole site through morning mist. Capture the view.", es:"La puerta donde ves por primera vez todo el sitio entre la niebla. Captura la vista." } },
          { id:"mp2", emoji:"📷", lat:-13.1631, lng:-72.5460,
            title:{ ja:"見張り小屋（定番の展望）", en:"Guardhouse (classic view)", es:"Casa del Guardián (vista clásica)" },
            narration:{ ja:"ハガキでおなじみの全景はここから。茅葺きの小屋越しに、段々畑と街、背後のワイナピチュが一望できる。", en:"The postcard panorama is from here — terraces, the city and Huayna Picchu beyond the thatched hut.", es:"La panorámica de postal es desde aquí: andenes, la ciudad y el Huayna Picchu tras la choza." },
            riddle:{ ja:"段々畑越しに遺跡とワイナピチュを見下ろす定番ポイント。その全景を撮ろう。", en:"The classic spot overlooking the ruins and Huayna Picchu over the terraces. Shoot the panorama.", es:"El punto clásico sobre las ruinas y el Huayna Picchu. Toma la panorámica." } },
          { id:"mp3", emoji:"☀️", lat:-13.1636, lng:-72.5450,
            title:{ ja:"太陽の神殿（トレオン）", en:"Temple of the Sun (Torreón)", es:"Templo del Sol (Torreón)" },
            narration:{ ja:"曲線の石壁を持つ唯一の建物。窓は冬至・夏至の太陽が差し込む位置に正確に開けられている。", en:"The only building with curved walls. Its windows align precisely to the solstice sunrises.", es:"El único edificio de muros curvos. Sus ventanas se alinean con los amaneceres del solsticio." },
            riddle:{ ja:"丸みを帯びた曲線の石壁を持つ神殿。その美しい曲面を撮ろう。", en:"The temple with smooth curved stone walls. Capture that curve.", es:"El templo de muros curvos de piedra. Captura esa curva." } },
          { id:"mp4", emoji:"🪨", lat:-13.1631, lng:-72.5455,
            title:{ ja:"インティワタナ（日時計の石）", en:"Intihuatana (the sun stone)", es:"Intihuatana (la piedra solar)" },
            narration:{ ja:"『太陽をつなぐ石』。天文観測と儀式に使われたとされる聖なる切り出し石。", en:"The 'hitching post of the sun' — a carved sacred stone used for astronomy and ritual.", es:"El 'amarradero del sol': piedra sagrada tallada para astronomía y ritual." },
            riddle:{ ja:"一枚岩から削り出された『太陽をつなぐ石』。その角ばった姿を撮ろう。", en:"The 'sun stone' carved from a single rock. Capture its angular form.", es:"La 'piedra solar' tallada de una sola roca. Captura su forma angular." } },
          { id:"mp5", emoji:"🪟", lat:-13.1639, lng:-72.5448,
            title:{ ja:"三つの窓の神殿", en:"Temple of the Three Windows", es:"Templo de las Tres Ventanas" },
            narration:{ ja:"聖なる広場に面し、台形の三つの窓が東の谷へ開く。インカの世界観を表すといわれる。", en:"Facing the sacred plaza, three trapezoidal windows open to the eastern valley — said to express the Inca worldview.", es:"Frente a la plaza sagrada, tres ventanas trapezoidales abren al valle este; expresan la cosmovisión inca." },
            riddle:{ ja:"東の谷へ開く三つの台形の窓。その窓の並びを撮ろう。", en:"Three trapezoidal windows opening to the valley. Shoot the row of windows.", es:"Tres ventanas trapezoidales hacia el valle. Toma la hilera de ventanas." } },
          { id:"mp6", emoji:"⛰️", lat:-13.1610, lng:-72.5447,
            title:{ ja:"聖なる岩とワイナピチュ", en:"Sacred Rock & Huayna Picchu", es:"Roca Sagrada y Huayna Picchu" },
            narration:{ ja:"背後の山の稜線をかたどったと言われる大岩。ここからワイナピチュへの登山道が始まる。", en:"A great stone said to echo the mountain ridge behind it. The Huayna Picchu trail begins here.", es:"Una gran roca que evoca la cresta de la montaña. Aquí inicia el sendero al Huayna Picchu." },
            riddle:{ ja:"背後の山の形をなぞったような大きな聖なる岩。山と岩を一緒に撮ろう。", en:"The large sacred rock echoing the mountain behind. Shoot the rock with the peak.", es:"La gran roca sagrada que imita la montaña. Toma la roca con el pico." } },
        ],
        history:[
          { emoji:"📜", title:{ ja:"インカ帝国の聖地", en:"Sacred site of the Inca", es:"Sitio sagrado inca" },
            body:{ ja:"15世紀半ば、皇帝パチャクテクの時代に築かれた王の離宮とも聖域ともいわれる。スペイン人には知られず破壊を免れた。", en:"Built in the mid-1400s under emperor Pachacuti as a royal estate or sanctuary. Unknown to the Spanish, it escaped destruction.", es:"Construido a mediados del siglo XV bajo Pachacútec como hacienda real o santuario. Desconocido por los españoles, se salvó." } },
          { emoji:"🧭", title:{ ja:"1911年の『再発見』", en:"The 1911 'rediscovery'", es:"El 'redescubrimiento' de 1911" },
            body:{ ja:"1911年、米国人ハイラム・ビンガムが世界に紹介。実際には地元の人々は存在を知っていた。", en:"Brought to world attention in 1911 by Hiram Bingham — though local people already knew it was there.", es:"Dado a conocer al mundo en 1911 por Hiram Bingham, aunque los locales ya conocían su existencia." } },
          { emoji:"🏗️", title:{ ja:"地震に強い石組みと段々畑", en:"Quake-proof stonework & terraces", es:"Cantería antisísmica y andenes" },
            body:{ ja:"モルタルを使わず石を精密に積む『乾式石積み』。段々畑は水はけと土壌流出を防ぎ、急斜面での農業を可能にした。", en:"Mortar-free 'dry stone' fitting. Terraces drained water and stopped erosion, enabling farming on steep slopes.", es:"Ensamble en seco sin mortero. Los andenes drenaban el agua y evitaban la erosión, permitiendo cultivar en pendientes." } },
        ],
      } },
    { id:"cusco", order:6, flag:"🇵🇪", lat:-13.517, lng:-71.978,
      name:{ ja:"クスコ歴史地区", en:"Cusco", es:"Cusco" },
      country:{ ja:"ペルー", en:"Peru", es:"Perú" } },
    { id:"angkor", order:7, flag:"🇰🇭", lat:13.412, lng:103.866,
      name:{ ja:"アンコール・ワット", en:"Angkor Wat", es:"Angkor Wat" },
      country:{ ja:"カンボジア", en:"Cambodia", es:"Camboya" } },
    { id:"rome", order:8, flag:"🇮🇹", lat:41.890, lng:12.492,
      name:{ ja:"ローマ歴史地区", en:"Historic Rome", es:"Roma histórica" },
      country:{ ja:"イタリア", en:"Italy", es:"Italia" } },
  ],

  // 国リスト（出身国・誇りに思う国 用。flag＋多言語名）
  countries: [
    {c:"JP",f:"🇯🇵",ja:"日本",en:"Japan",es:"Japón"},
    {c:"GT",f:"🇬🇹",ja:"グアテマラ",en:"Guatemala",es:"Guatemala"},
    {c:"US",f:"🇺🇸",ja:"アメリカ",en:"USA",es:"Estados Unidos"},
    {c:"CA",f:"🇨🇦",ja:"カナダ",en:"Canada",es:"Canadá"},
    {c:"MX",f:"🇲🇽",ja:"メキシコ",en:"Mexico",es:"México"},
    {c:"ES",f:"🇪🇸",ja:"スペイン",en:"Spain",es:"España"},
    {c:"FR",f:"🇫🇷",ja:"フランス",en:"France",es:"Francia"},
    {c:"DE",f:"🇩🇪",ja:"ドイツ",en:"Germany",es:"Alemania"},
    {c:"GB",f:"🇬🇧",ja:"イギリス",en:"UK",es:"Reino Unido"},
    {c:"IT",f:"🇮🇹",ja:"イタリア",en:"Italy",es:"Italia"},
    {c:"NL",f:"🇳🇱",ja:"オランダ",en:"Netherlands",es:"Países Bajos"},
    {c:"CH",f:"🇨🇭",ja:"スイス",en:"Switzerland",es:"Suiza"},
    {c:"PT",f:"🇵🇹",ja:"ポルトガル",en:"Portugal",es:"Portugal"},
    {c:"IE",f:"🇮🇪",ja:"アイルランド",en:"Ireland",es:"Irlanda"},
    {c:"SE",f:"🇸🇪",ja:"スウェーデン",en:"Sweden",es:"Suecia"},
    {c:"NO",f:"🇳🇴",ja:"ノルウェー",en:"Norway",es:"Noruega"},
    {c:"AU",f:"🇦🇺",ja:"オーストラリア",en:"Australia",es:"Australia"},
    {c:"NZ",f:"🇳🇿",ja:"ニュージーランド",en:"New Zealand",es:"Nueva Zelanda"},
    {c:"BR",f:"🇧🇷",ja:"ブラジル",en:"Brazil",es:"Brasil"},
    {c:"AR",f:"🇦🇷",ja:"アルゼンチン",en:"Argentina",es:"Argentina"},
    {c:"CL",f:"🇨🇱",ja:"チリ",en:"Chile",es:"Chile"},
    {c:"CO",f:"🇨🇴",ja:"コロンビア",en:"Colombia",es:"Colombia"},
    {c:"PE",f:"🇵🇪",ja:"ペルー",en:"Peru",es:"Perú"},
    {c:"CR",f:"🇨🇷",ja:"コスタリカ",en:"Costa Rica",es:"Costa Rica"},
    {c:"SV",f:"🇸🇻",ja:"エルサルバドル",en:"El Salvador",es:"El Salvador"},
    {c:"HN",f:"🇭🇳",ja:"ホンジュラス",en:"Honduras",es:"Honduras"},
    {c:"NI",f:"🇳🇮",ja:"ニカラグア",en:"Nicaragua",es:"Nicaragua"},
    {c:"BZ",f:"🇧🇿",ja:"ベリーズ",en:"Belize",es:"Belice"},
    {c:"KR",f:"🇰🇷",ja:"韓国",en:"Korea",es:"Corea"},
    {c:"CN",f:"🇨🇳",ja:"中国",en:"China",es:"China"},
    {c:"TW",f:"🇹🇼",ja:"台湾",en:"Taiwan",es:"Taiwán"},
    {c:"TH",f:"🇹🇭",ja:"タイ",en:"Thailand",es:"Tailandia"},
    {c:"IN",f:"🇮🇳",ja:"インド",en:"India",es:"India"},
    {c:"IL",f:"🇮🇱",ja:"イスラエル",en:"Israel",es:"Israel"},
    {c:"ZA",f:"🇿🇦",ja:"南アフリカ",en:"South Africa",es:"Sudáfrica"},
    {c:"PL",f:"🇵🇱",ja:"ポーランド",en:"Poland",es:"Polonia"},
  ],
};
