// Mi Amigo — 多言語データ（日本語 / English / Español）
// 写真は img フィールドに "img/<id>.jpg" or 画像URL。未指定は emoji プレースホルダー。
// 価格(price)は USD のおおよその目安。
window.MI_AMIGO_DATA = {
  listings: [
    { id:"delagente-coffee", type:"exp", emoji:"☕", price:40, unit:"USD", maxSlots:8,
      area:"San Miguel Escobar（アンティグア近郊）", link:"https://www.delagente.org/", img:"",
      title:{ ja:"De La Gente コーヒー農園＆コミュニティ体験", en:"De La Gente Coffee Farm & Community Tour", es:"Finca de café y comunidad De La Gente" },
      desc:{ ja:"生産者協同組合と歩く社会的企業のツアー。摘み取り〜焙煎、コミュニティ支援の現場まで",
             en:"A social-enterprise tour with farmer cooperatives: from picking to roasting, and the community behind it.",
             es:"Un tour de empresa social con cooperativas: de la cosecha al tueste, y la comunidad detrás." } },
    { id:"chocomuseo-bar", type:"exp", emoji:"🍫", price:33, unit:"USD", maxSlots:12,
      area:"4a calle oriente", link:"https://www.chocomuseo.com/", img:"",
      title:{ ja:"ChocoMuseo Bean-to-Bar チョコ ワークショップ", en:"ChocoMuseo Bean-to-Bar Chocolate Workshop", es:"Taller de chocolate Bean-to-Bar ChocoMuseo" },
      desc:{ ja:"カカオ豆から板チョコまで（約2時間）。手作り120gをお持ち帰り",
             en:"From cacao bean to bar (about 2 hours). Take home 120g you made yourself.",
             es:"Del grano de cacao a la barra (unas 2 horas). Llévate 120g hechos por ti." } },
    { id:"kakaw-weaving", type:"exp", emoji:"🧵", price:45, unit:"USD", maxSlots:5,
      area:"アンティグア中心部 / Antigua centro", link:"https://kakawdesigns.com/", img:"",
      title:{ ja:"Kakaw Designs バックストラップ織り ワークショップ", en:"Kakaw Designs Backstrap Weaving Workshop", es:"Taller de telar de cintura Kakaw Designs" },
      desc:{ ja:"マヤの腰機織りを庭で学ぶ（英・西対応）。福祉×ウイピル アップサイクルと連動",
             en:"Learn Maya backstrap weaving in a garden (EN/ES). Linked to our huipil upcycling project.",
             es:"Aprende el telar de cintura maya en un jardín (EN/ES). Ligado a nuestro proyecto de huipil." } },
    { id:"food-tour", type:"exp", emoji:"🥘", price:55, unit:"USD", maxSlots:10,
      area:"アンティグア旧市街 / Antigua casco", link:"", img:"",
      title:{ ja:"アンティグア ストリートフード ツアー", en:"Antigua Street Food Tour", es:"Tour de comida callejera de Antigua" },
      desc:{ ja:"ガイドと市場〜名店を巡り約10品を試食。少人数制",
             en:"Taste about 10 dishes from market to favorite spots with a guide. Small groups.",
             es:"Prueba unos 10 platillos del mercado a los mejores lugares con un guía. Grupos pequeños." } },
    { id:"kombu-ramen", type:"food", emoji:"🍜", price:14, unit:"USD", maxSlots:16,
      area:"3a calle oriente #19D", link:"https://komburamenshop.com/", img:"",
      title:{ ja:"Kombu Ramen Shop 席予約", en:"Kombu Ramen Shop Reservation", es:"Reserva en Kombu Ramen Shop" },
      desc:{ ja:"グアテマラ初のラーメン店。地元産小麦の自家製麺と6種のラーメン",
             en:"Guatemala's first ramen shop. House-made noodles from local flour, 6 kinds of ramen.",
             es:"El primer ramen de Guatemala. Fideos caseros de harina local y 6 tipos de ramen." } },
    { id:"barbara-hostel", type:"stay", emoji:"🛏️", price:15, unit:"USD", maxSlots:10,
      area:"アンティグア中心部 / Antigua centro", link:"", img:"",
      title:{ ja:"Barbara's Boutique Hostel（1泊・ドミトリー）", en:"Barbara's Boutique Hostel (dorm, 1 night)", es:"Barbara's Boutique Hostel (dormitorio, 1 noche)" },
      desc:{ ja:"コロニアル様式の邸宅。屋上テラスからアグア・フエゴ・アカテナンゴの3火山",
             en:"A colonial house with a rooftop overlooking the Agua, Fuego and Acatenango volcanoes.",
             es:"Una casa colonial con azotea y vista a los volcanes Agua, Fuego y Acatenango." } },
  ],

  // 謎解きの全体情報（謎は下の guide.route.stops から生成）
  quest: {
    title:  { ja:"アンティグア 歴史ミステリー・ラリー", en:"Antigua History Mystery Rally", es:"Rally del misterio histórico de Antigua" },
    reward: { ja:"全スポット制覇で限定ステッカー＋次回10%OFF", en:"Complete all spots for a sticker + 10% off next time", es:"Completa todo: sticker + 10% de descuento la próxima vez" },
  },

  // 音声ウォーキングガイド ＝ 謎解きスポット（多言語）
  guide: {
    route: {
      title: { ja:"アンティグア 街歩き音声ガイド", en:"Antigua Walking Audio Guide", es:"Audioguía a pie de Antigua" },
      intro: {
        ja:"世界遺産の街アンティグアを約10スポット巡ります。再生すると物語が流れ、謎解きでは“その場所”の写真を撮って投稿します。",
        en:"Walk the UNESCO city of Antigua across ~10 stops. Play to hear each story; in the rally, photograph the place and post it.",
        es:"Recorre la ciudad Patrimonio de Antigua en ~10 paradas. Reproduce para oír la historia; en el rally, fotografía el lugar y publícalo.",
      },
      stops: [
        { id:"s1", emoji:"🌉", lat:14.5586, lng:-90.7339,
          title:{ ja:"サンタ・カタリナのアーチ", en:"Santa Catalina Arch", es:"Arco de Santa Catalina" },
          text:{ ja:"アンティグアの象徴、黄色いアーチ。17世紀、修道女たちが通りに姿を見せず行き来できるよう、修道院と学校をつなぐ橋として造られました。背後にはアグア火山がそびえます。",
                 en:"Antigua's icon, the yellow arch. Built in the 17th century so cloistered nuns could cross the street unseen, linking the convent and school. Volcán de Agua rises behind it.",
                 es:"El ícono de Antigua, el arco amarillo. Construido en el siglo XVII para que las monjas de clausura cruzaran la calle sin ser vistas. Detrás se alza el Volcán de Agua." },
          riddle:{ ja:"修道女たちが人目を避けて通りを渡れるよう造られた『黄色いアーチ』。その姿を写真に撮ろう。",
                   en:"Find the yellow arch built so cloistered nuns could cross the street unseen. Photograph it.",
                   es:"Encuentra el arco amarillo hecho para que las monjas cruzaran sin ser vistas. Fotografíalo." } },
        { id:"s2", emoji:"⛲", lat:14.5564, lng:-90.7339,
          title:{ ja:"中央公園（プラサ・マヨール）", en:"Central Park (Plaza Mayor)", es:"Parque Central (Plaza Mayor)" },
          text:{ ja:"街の心臓部。中央には「人魚の噴水」が立ち、大聖堂や旧総督府に囲まれています。人々が集い、休む、アンティグアの暮らしの中心です。",
                 en:"The heart of the city. At its center stands the Fountain of the Sirens, surrounded by the cathedral and old palaces.",
                 es:"El corazón de la ciudad. En su centro está la Fuente de las Sirenas, rodeada por la catedral y los palacios." },
          riddle:{ ja:"街の中心、『人魚の噴水』が立つ広場。噴水を写真に撮ろう。",
                   en:"The central plaza with the Fountain of the Sirens. Photograph the fountain.",
                   es:"La plaza central con la Fuente de las Sirenas. Fotografía la fuente." } },
        { id:"s3", emoji:"⛪", lat:14.5566, lng:-90.7327,
          title:{ ja:"サン・ホセ大聖堂（旧聖堂跡）", en:"Cathedral of San José (ruins)", es:"Catedral de San José (ruinas)" },
          text:{ ja:"かつて中米最大級を誇った聖堂。1773年の大地震で崩れ、今もその壮大な廃墟が残ります。",
                 en:"Once among the grandest cathedrals in Central America, toppled by the 1773 earthquake. Its majestic ruins still stand.",
                 es:"Una de las catedrales más grandiosas de Centroamérica, derribada por el terremoto de 1773. Sus ruinas aún se alzan." },
          riddle:{ ja:"1773年の地震で崩れた、かつて中米最大級の聖堂跡。その廃墟を写真に撮ろう。",
                   en:"The ruins of what was one of Central America's grandest cathedrals, felled in 1773. Photograph them.",
                   es:"Las ruinas de una de las mayores catedrales, caída en 1773. Fotografíalas." } },
        { id:"s4", emoji:"🏛️", lat:14.5560, lng:-90.7335,
          title:{ ja:"総督府（カピタネス・ヘネラレス宮殿）", en:"Palace of the Captains General", es:"Palacio de los Capitanes Generales" },
          text:{ ja:"スペイン植民地時代、グアテマラ総督領を治めた政庁。長く連なるアーチの回廊が当時の権力を物語ります。",
                 en:"The seat of Spanish colonial government. Its long arcade of arches speaks to the reach of that power.",
                 es:"La sede del gobierno colonial español. Su larga arcada habla del alcance de aquel poder." },
          riddle:{ ja:"長いアーチの回廊が続く、植民地時代の総督府。その回廊を写真に撮ろう。",
                   en:"The colonial palace with a long arcade of arches. Photograph the arcade.",
                   es:"El palacio colonial con una larga arcada. Fotografía la arcada." } },
        { id:"s5", emoji:"💛", lat:14.5601, lng:-90.7344,
          title:{ ja:"ラ・メルセー教会", en:"La Merced Church", es:"Iglesia de La Merced" },
          text:{ ja:"鮮やかな黄色と白の漆喰装飾が美しいバロック教会。地震に耐えるよう低く頑丈に設計されました。",
                 en:"A Baroque church famed for its vivid yellow facade and white stucco, built low and strong to resist earthquakes.",
                 es:"Una iglesia barroca célebre por su fachada amarilla y estuco blanco, baja y fuerte contra terremotos." },
          riddle:{ ja:"鮮やかな黄色のバロック教会。その正面（ファサード）を写真に撮ろう。",
                   en:"The vivid yellow Baroque church. Photograph its facade.",
                   es:"La iglesia barroca amarilla. Fotografía su fachada." } },
        { id:"s6", emoji:"🏚️", lat:14.5588, lng:-90.7316,
          title:{ ja:"カプチナス修道院", en:"Las Capuchinas Convent", es:"Convento de las Capuchinas" },
          text:{ ja:"保存状態の良い修道院。円形に並ぶ修道女の小部屋「塔」が珍しく、静寂と祈りの暮らしを今に伝えます。",
                 en:"A well-preserved convent. Its unusual circular 'tower' of nuns' cells conveys a life of silence and prayer.",
                 es:"Un convento bien conservado. Su singular 'torre' circular de celdas evoca el silencio y la oración." },
          riddle:{ ja:"円形に小部屋が並ぶ珍しい修道院。その中庭か塔を写真に撮ろう。",
                   en:"The convent with an unusual circular tower of cells. Photograph the courtyard or tower.",
                   es:"El convento con una torre circular de celdas. Fotografía el patio o la torre." } },
        { id:"s7", emoji:"✝️", lat:14.5650, lng:-90.7300,
          title:{ ja:"クルスの丘（展望台）", en:"Hill of the Cross (viewpoint)", es:"Cerro de la Cruz (mirador)" },
          text:{ ja:"街を見下ろす丘の上の十字架。アンティグアの碁盤の街並みと、その先のアグア火山が一直線に並ぶ絶景です。",
                 en:"A cross on the hill above the city, where Antigua's grid lines up with Volcán de Agua beyond.",
                 es:"Una cruz sobre la colina, donde la cuadrícula de Antigua se alinea con el Volcán de Agua." },
          riddle:{ ja:"丘の上の十字架から、街とアグア火山が一直線に見える展望。その景色を写真に撮ろう。",
                   en:"The hilltop cross where city and Volcán de Agua align. Photograph the view.",
                   es:"La cruz en la colina donde la ciudad y el volcán se alinean. Fotografía la vista." } },
        { id:"s8", emoji:"🙏", lat:14.5535, lng:-90.7313,
          title:{ ja:"サン・フランシスコ教会（エルマノ・ペドロ）", en:"San Francisco Church (Hermano Pedro)", es:"Iglesia de San Francisco (Hermano Pedro)" },
          text:{ ja:"中米初の聖人、エルマノ・ペドロが眠る巡礼地。今も多くの人が願いを胸に祈りを捧げます。",
                 en:"A pilgrimage site holding the tomb of Hermano Pedro, the first saint of Central America.",
                 es:"Un sitio de peregrinación con la tumba del Hermano Pedro, el primer santo de Centroamérica." },
          riddle:{ ja:"中米初の聖人エルマノ・ペドロが眠る教会。その外観を写真に撮ろう。",
                   en:"The church holding the tomb of Hermano Pedro, the first saint. Photograph its exterior.",
                   es:"La iglesia con la tumba del Hermano Pedro. Fotografía su exterior." } },
        { id:"s9", emoji:"💧", lat:14.5560, lng:-90.7300,
          title:{ ja:"タンケ・ラ・ウニオン（洗濯場）", en:"Tanque La Unión (wash basins)", es:"Tanque La Unión (lavaderos)" },
          text:{ ja:"石造りの公共洗濯場。植民地時代から人々が洗濯や語らいに集った場所で、今も地元の暮らしが息づいています。",
                 en:"Public stone wash basins where people have gathered to wash and talk since colonial times.",
                 es:"Lavaderos públicos de piedra donde la gente se reúne a lavar y conversar desde la colonia." },
          riddle:{ ja:"今も使われる石造りの公共洗濯場。その水場を写真に撮ろう。",
                   en:"The stone public wash basins still in use today. Photograph them.",
                   es:"Los lavaderos públicos de piedra aún en uso. Fotografíalos." } },
        { id:"s10", emoji:"🧶", lat:14.5558, lng:-90.7352,
          title:{ ja:"工芸市場（ウイピルの織物）", en:"Crafts Market (Huipil textiles)", es:"Mercado de Artesanías (huipiles)" },
          text:{ ja:"色鮮やかなマヤの織物「ウイピル」が並ぶ市場。一枚一枚が村ごとの模様を持ち、作り手の物語を宿しています。",
                 en:"A market bright with Maya 'huipil' textiles, each carrying the pattern of its village.",
                 es:"Un mercado lleno de textiles mayas 'huipiles', cada uno con el patrón de su pueblo." },
          riddle:{ ja:"色鮮やかなウイピルが並ぶ工芸市場。お気に入りの織物を写真に撮ろう。",
                   en:"The crafts market full of colorful huipiles. Photograph your favorite textile.",
                   es:"El mercado de artesanías lleno de huipiles. Fotografía tu textil favorito." } },
      ],
    },
    // 歴史を聴くシリーズ（場所に縛られない音声）
    history: [
      { id:"h1", emoji:"📜",
        title:{ ja:"グアテマラ小史", en:"A Short History of Guatemala", es:"Breve historia de Guatemala" },
        text:{ ja:"マヤ文明の地に、1524年スペインのアルバラードが征服者として現れ、植民地時代が始まりました。1821年に独立。先住民の文化と植民の歴史が、今のグアテマラに重なっています。",
               en:"On the land of the Maya, the Spaniard Alvarado arrived as conqueror in 1524, beginning the colonial era. Independence came in 1821.",
               es:"En tierra maya, el español Alvarado llegó como conquistador en 1524, iniciando la época colonial. La independencia llegó en 1821." } },
      { id:"h2", emoji:"🌋",
        title:{ ja:"アンティグア、遷都の物語", en:"Antigua: Why the Capital Moved", es:"Antigua: por qué se mudó la capital" },
        text:{ ja:"この街はかつて「サンティアゴ・デ・ロス・カバジェロス」という首都でした。1773年のサンタ・マルタ大地震で甚大な被害を受け、首都は現在のグアテマラシティへ移転。残されたこの街は「ラ・アンティグア（古い都）」と呼ばれるようになりました。",
               en:"This city was once the capital, 'Santiago de los Caballeros.' The 1773 earthquakes devastated it, the capital moved to today's Guatemala City, and what remained became 'La Antigua'.",
               es:"Esta ciudad fue la capital, 'Santiago de los Caballeros'. Los terremotos de 1773 la devastaron, la capital se trasladó y lo que quedó se llamó 'La Antigua'." } },
    ],
  },

  // なかま（コミュニティ）— デモのグループとメッセージ（ワールドホステル風）
  community: {
    groups: [
      { id:"g-tour", emoji:"🏛️", name:{ ja:"アンティグア世界遺産ツアー", en:"Antigua Heritage Tour", es:"Tour Patrimonio de Antigua" },
        seed:[
          { from:"Lucía", emoji:"🦜", text:"¡Hola amigos! ¿Alguien sube al Cerro de la Cruz al atardecer? 🌋" },
          { from:"Ken", emoji:"🎒", text:"行きたい！何時集合？" },
          { from:"Mia", emoji:"📷", text:"Just got the yellow arch shot, it's glowing today ✨" },
        ] },
      { id:"g-cafe", emoji:"☕", name:{ ja:"カフェ好き Amigos", en:"Café Amigos", es:"Amigos del café" },
        seed:[
          { from:"Sofía", emoji:"☕", text:"Fat Cat tiene el mejor cortado 👌" },
          { from:"Tomo", emoji:"🍰", text:"12 Onzas のケーキ最高だった！" },
        ] },
      { id:"g-lounge", emoji:"🌏", name:{ ja:"旅人ラウンジ", en:"Traveler Lounge", es:"Sala de viajeros" },
        seed:[
          { from:"Diego", emoji:"🎸", text:"Live music at the hostel tonight, todos invitados!" },
          { from:"Anna", emoji:"🌻", text:"Anyone heading to Lake Atitlán this weekend?" },
        ] },
    ],
  },

  // 国リスト（出身国・誇りに思う国 用。flag＋多言語名）
  countries: [
    {c:"JP",f:"🇯🇵",ja:"日本",en:"Japan",es:"Japón"},
    {c:"GT",f:"🇬🇹",ja:"グアテマラ",en:"Guatemala",es:"Guatemala"},
    {c:"US",f:"🇺🇸",ja:"アメリカ",en:"USA",es:"Estados Unidos"},
    {c:"CA",f:"🇨🇦",ja:"カナダ",en:"Canada",es:"Canadá"},
    {c:"MX",f:"🇲🇽",ja:"メキシコ",en:"Mexico",es:"México"},
    {c:"ES",f:"🇪🇸",ja:"スペイン",en:"Spain",es:"España"},
    {c:"FR",f:"🇫🇷",ja:"フランス",en:"France",es:"Francia"},
    {c:"DE",f:"🇩🇪",ja:"ドイツ",en:"Germany",es:"Alemania"},
    {c:"GB",f:"🇬🇧",ja:"イギリス",en:"UK",es:"Reino Unido"},
    {c:"IT",f:"🇮🇹",ja:"イタリア",en:"Italy",es:"Italia"},
    {c:"NL",f:"🇳🇱",ja:"オランダ",en:"Netherlands",es:"Países Bajos"},
    {c:"CH",f:"🇨🇭",ja:"スイス",en:"Switzerland",es:"Suiza"},
    {c:"PT",f:"🇵🇹",ja:"ポルトガル",en:"Portugal",es:"Portugal"},
    {c:"IE",f:"🇮🇪",ja:"アイルランド",en:"Ireland",es:"Irlanda"},
    {c:"SE",f:"🇸🇪",ja:"スウェーデン",en:"Sweden",es:"Suecia"},
    {c:"NO",f:"🇳🇴",ja:"ノルウェー",en:"Norway",es:"Noruega"},
    {c:"AU",f:"🇦🇺",ja:"オーストラリア",en:"Australia",es:"Australia"},
    {c:"NZ",f:"🇳🇿",ja:"ニュージーランド",en:"New Zealand",es:"Nueva Zelanda"},
    {c:"BR",f:"🇧🇷",ja:"ブラジル",en:"Brazil",es:"Brasil"},
    {c:"AR",f:"🇦🇷",ja:"アルゼンチン",en:"Argentina",es:"Argentina"},
    {c:"CL",f:"🇨🇱",ja:"チリ",en:"Chile",es:"Chile"},
    {c:"CO",f:"🇨🇴",ja:"コロンビア",en:"Colombia",es:"Colombia"},
    {c:"PE",f:"🇵🇪",ja:"ペルー",en:"Peru",es:"Perú"},
    {c:"CR",f:"🇨🇷",ja:"コスタリカ",en:"Costa Rica",es:"Costa Rica"},
    {c:"SV",f:"🇸🇻",ja:"エルサルバドル",en:"El Salvador",es:"El Salvador"},
    {c:"HN",f:"🇭🇳",ja:"ホンジュラス",en:"Honduras",es:"Honduras"},
    {c:"NI",f:"🇳🇮",ja:"ニカラグア",en:"Nicaragua",es:"Nicaragua"},
    {c:"BZ",f:"🇧🇿",ja:"ベリーズ",en:"Belize",es:"Belice"},
    {c:"KR",f:"🇰🇷",ja:"韓国",en:"Korea",es:"Corea"},
    {c:"CN",f:"🇨🇳",ja:"中国",en:"China",es:"China"},
    {c:"TW",f:"🇹🇼",ja:"台湾",en:"Taiwan",es:"Taiwán"},
    {c:"TH",f:"🇹🇭",ja:"タイ",en:"Thailand",es:"Tailandia"},
    {c:"IN",f:"🇮🇳",ja:"インド",en:"India",es:"India"},
    {c:"IL",f:"🇮🇱",ja:"イスラエル",en:"Israel",es:"Israel"},
    {c:"ZA",f:"🇿🇦",ja:"南アフリカ",en:"South Africa",es:"Sudáfrica"},
    {c:"PL",f:"🇵🇱",ja:"ポーランド",en:"Poland",es:"Polonia"},
  ],
};
